package bindings.commons.automation.aio.rest.dto.gdpr;

public enum ConsentName {
  MARKETING_IM,
  MARKETING_PAPER_MAIL,
  MARKETING_PUSH,
  MARKETING_IPFD,
  MARKETING_DATA_TRANSFER,
  MARKETING_SMS,
  MARKETING_EMAIL,
  MARKETING_ROBO,
  MARKETING_PHONE,
  MARKETING_3RD_PARTY,
  ASIAKASTIETO_DATAPOOL,
  DELTA_VISTA_PROCESSING,
  MC_BLACKLIST,
  MARKETING_FROM_LEADS,
  DELTA_VISTA_VERIFICATION
}
