//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.23 at 04:21:53 PM CET
//


package bindings.commons.automation.mule.model.mule.development.documents.aio.channel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ipfdigital.automation.mule.model.mule.development.documents.aio.channel
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.ipfdigital.automation.mule.model.mule.development.documents.aio.channel
   * 
   */
  public ObjectFactory() {
    // New ObjectFactory
  }

  /**
   * Create an instance of {@link UploadDocumentsRequest }
   * 
   */
  public UploadDocumentsRequest createUploadDocumentsRequest() {
    return new UploadDocumentsRequest();
  }

  /**
   * Create an instance of {@link UploadDocumentsRequest.Body }
   * 
   */
  public UploadDocumentsRequest.Body createUploadDocumentsRequestBody() {
    return new UploadDocumentsRequest.Body();
  }

  /**
   * Create an instance of {@link UploadDocumentsResponse }
   * 
   */
  public UploadDocumentsResponse createUploadDocumentsResponse() {
    return new UploadDocumentsResponse();
  }

  /**
   * Create an instance of {@link StatusResponseType }
   * 
   */
  public StatusResponseType createStatusResponseType() {
    return new StatusResponseType();
  }

  /**
   * Create an instance of {@link UploadDocumentsRequest.Body.Keys }
   * 
   */
  public UploadDocumentsRequest.Body.Keys createUploadDocumentsRequestBodyKeys() {
    return new UploadDocumentsRequest.Body.Keys();
  }

}
