//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.23 at 04:21:53 PM CET
//


package bindings.commons.automation.mule.model.mule.development.documents.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="fileType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                   &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
 *                   &lt;element name="keys" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "body"
})
@XmlRootElement(name = "UploadDocumentsRequest")
public class UploadDocumentsRequest {

  @XmlElement(required = true)
  protected Body body;

  /**
   * Gets the value of the body property.
   *
   * @return possible object is {@link Body }
   *
   */
  public Body getBody() {
    return this.body;
  }

  /**
   * Sets the value of the body property.
   *
   * @param value allowed object is {@link Body }
   *
   */
  public void setBody(final Body value) {
    this.body = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   *
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="path" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="contentType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *         &lt;element name="fileType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *         &lt;element name="content" type="{http://www.w3.org/2001/XMLSchema}base64Binary"/&gt;
   *         &lt;element name="keys" maxOccurs="unbounded"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   *
   *
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "fileName",
      "path",
      "contentType",
      "fileType",
      "content",
      "keys"
  })
  public static class Body {

    @XmlElement(required = true)
    protected String fileName;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(required = true)
    protected String contentType;
    protected String fileType;
    @XmlElement(required = true)
    protected byte[] content;
    @XmlElement(required = true)
    protected List<Keys> keys;

    /**
     * Gets the value of the fileName property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFileName() {
      return this.fileName;
    }

    /**
     * Sets the value of the fileName property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFileName(final String value) {
      this.fileName = value;
    }

    /**
     * Gets the value of the path property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getPath() {
      return this.path;
    }

    /**
     * Sets the value of the path property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setPath(final String value) {
      this.path = value;
    }

    /**
     * Gets the value of the contentType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getContentType() {
      return this.contentType;
    }

    /**
     * Sets the value of the contentType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setContentType(final String value) {
      this.contentType = value;
    }

    /**
     * Gets the value of the fileType property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getFileType() {
      return this.fileType;
    }

    /**
     * Sets the value of the fileType property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setFileType(final String value) {
      this.fileType = value;
    }

    /**
     * Gets the value of the content property.
     *
     * @return possible object is byte[]
     */
    public byte[] getContent() {
      return this.content;
    }

    /**
     * Sets the value of the content property.
     *
     * @param value allowed object is byte[]
     */
    public void setContent(final byte[] value) {
      this.content = value;
    }

    /**
     * Gets the value of the keys property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the keys property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getKeys().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Keys }
     *
     *
     */
    public List<Keys> getKeys() {
      if (this.keys == null) {
        this.keys = new ArrayList<>();
      }
      return this.keys;
    }

    public void setKeys(final List<Keys> keys) {
      this.keys = keys;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type",
        "value"
    })
    public static class Keys {

      @XmlElement(required = true)
      protected String type;
      @XmlElement(required = true)
      protected String value;

      public Keys() {
        // for JAX marshalling
      }

      public Keys(final String type, final String value) {
        this.type = type;
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return this.type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setType(final String value) {
        this.type = value;
      }

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return this.value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setValue(final String value) {
        this.value = value;
      }

    }

  }

}
