package bindings.commons.automation.aio.rest.dto;

public enum LoanPurpose {
  KITCHEN_APPLIANCES,
  HOME_ENTERTAINMENT,
  APPLIANCE_REPAIR,
  FURNITURE_PURCHASE,
  TOOLS_GARDEN_EQUIPMENT,
  KITCHEN_RENOVATION,
  BATHROOM_RENOVATION,
  BEDROOM_RENOVATION,
  LIVING_ROOM_RENOVATION,
  OUTDOOR_LANDSCAPE,
  FINANCING_BIG_PURCHASE,
  TRAVELING_VACATION,
  DAILY_EXPENDITURE,
  EDUCATION_TRAINING,
  FINANCING_OTHER_LOANS,
  HOME_REPAIR_CONSTRUCTION,
  CAR_REPAIR_OR_PURCHASE,
  MEDICAL_EXPENCES,
  FAMILY,
  BUSINESS,
  THIRD_PARTY,
  OTHER
}
