package bindings.commons.automation.aio.rest.dto;

public enum OccupationType {
  EMPLOYEE,
  MANAGER,
  EXECUTIVE,
  SPECIALIST,
  OFFICE_CLERK,
  GOVERNMENT_OFFICIAL,
  LOWER_OFFICIAL,
  HIGHER_OFFICIAL,
  WORKER,
  SPECIALIST_OFFICE_WORKER,
  SENIOR_SPECIALIST,
  MIDDLE_MANAGER,
  TOP_MANAGER,
  OWNER_OF_COMPANY_SHAREHOLDER,
  WORKING_STUDENT,
  OTHER,
}
