//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.13 at 01:16:05 PM CEST
//


package bindings.commons.automation.mule.model.mule.development.collection.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for addressType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="door" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressType", propOrder = {
    "country",
    "city",
    "street",
    "door",
    "postcode"
})
public class AddressType {

  @XmlElement(required = true)
  protected String country;
  @XmlElement(required = true)
  protected String city;
  @XmlElement(required = true)
  protected String street;
  protected String door;
  protected String postcode;

  /**
   * Gets the value of the country property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCountry() {
    return this.country;
  }

  /**
   * Sets the value of the country property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCountry(final String value) {
    this.country = value;
  }

  /**
   * Gets the value of the city property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCity() {
    return this.city;
  }

  /**
   * Sets the value of the city property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCity(final String value) {
    this.city = value;
  }

  /**
   * Gets the value of the street property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getStreet() {
    return this.street;
  }

  /**
   * Sets the value of the street property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setStreet(final String value) {
    this.street = value;
  }

  /**
   * Gets the value of the door property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getDoor() {
    return this.door;
  }

  /**
   * Sets the value of the door property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setDoor(final String value) {
    this.door = value;
  }

  /**
   * Gets the value of the postcode property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getPostcode() {
    return this.postcode;
  }

  /**
   * Sets the value of the postcode property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setPostcode(final String value) {
    this.postcode = value;
  }

}
