//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.13 at 01:16:05 PM CEST
//


package bindings.commons.automation.mule.model.mule.development.collection.aio.channel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ipfdigital.automation.mule.model.mule.development.collection.aio.channel
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.ipfdigital.automation.mule.model.mule.development.collection.aio.channel
   * 
   */
  public ObjectFactory() {
    // New object factory
  }

  /**
   * Create an instance of {@link UploadCollectionOrderBatchRequest }
   * 
   */
  public UploadCollectionOrderBatchRequest createUploadCollectionOrderBatchRequest() {
    return new UploadCollectionOrderBatchRequest();
  }

  /**
   * Create an instance of {@link UploadCollectionOrderToSellBatchRequest }
   * 
   */
  public UploadCollectionOrderToSellBatchRequest createUploadCollectionOrderToSellBatchRequest() {
    return new UploadCollectionOrderToSellBatchRequest();
  }

  /**
   * Create an instance of {@link UploadCollectionOrderToSellBatchRequest.CollectionOrdersData }
   * 
   */
  public UploadCollectionOrderToSellBatchRequest.CollectionOrdersData createUploadCollectionOrderToSellBatchRequestCollectionOrdersData() {
    return new UploadCollectionOrderToSellBatchRequest.CollectionOrdersData();
  }

  /**
   * Create an instance of
   * {@link UploadCollectionOrderToSellBatchRequest.CollectionOrdersData.CollectionOrderData }
   * 
   */
  public UploadCollectionOrderToSellBatchRequest.CollectionOrdersData.CollectionOrderData createUploadCollectionOrderToSellBatchRequestCollectionOrdersDataCollectionOrderData() {
    return new UploadCollectionOrderToSellBatchRequest.CollectionOrdersData.CollectionOrderData();
  }

  /**
   * Create an instance of {@link UploadCollectionOrderBatchRequest.Body }
   * 
   */
  public UploadCollectionOrderBatchRequest.Body createUploadCollectionOrderBatchRequestBody() {
    return new UploadCollectionOrderBatchRequest.Body();
  }

  /**
   * Create an instance of
   * {@link UploadCollectionOrderBatchRequest.Body.CollectionOrderTerminations }
   * 
   */
  public UploadCollectionOrderBatchRequest.Body.CollectionOrderTerminations createUploadCollectionOrderBatchRequestBodyCollectionOrderTerminations() {
    return new UploadCollectionOrderBatchRequest.Body.CollectionOrderTerminations();
  }

  /**
   * Create an instance of {@link HeaderType }
   * 
   */
  public HeaderType createHeaderType() {
    return new HeaderType();
  }

  /**
   * Create an instance of {@link UploadCollectionOrderBatchResponse }
   * 
   */
  public UploadCollectionOrderBatchResponse createUploadCollectionOrderBatchResponse() {
    return new UploadCollectionOrderBatchResponse();
  }

  /**
   * Create an instance of {@link StatusResponseType }
   * 
   */
  public StatusResponseType createStatusResponseType() {
    return new StatusResponseType();
  }

  /**
   * Create an instance of {@link UploadCollectionOrderToSellBatchResponse }
   * 
   */
  public UploadCollectionOrderToSellBatchResponse createUploadCollectionOrderToSellBatchResponse() {
    return new UploadCollectionOrderToSellBatchResponse();
  }

  /**
   * Create an instance of {@link AddressType }
   * 
   */
  public AddressType createAddressType() {
    return new AddressType();
  }

  /**
   * Create an instance of
   * {@link UploadCollectionOrderToSellBatchRequest.CollectionOrdersData.CollectionOrderData.CollectionOrderDataBody }
   * 
   */
  public UploadCollectionOrderToSellBatchRequest.CollectionOrdersData.CollectionOrderData.CollectionOrderDataBody createUploadCollectionOrderToSellBatchRequestCollectionOrdersDataCollectionOrderDataCollectionOrderDataBody() {
    return new UploadCollectionOrderToSellBatchRequest.CollectionOrdersData.CollectionOrderData.CollectionOrderDataBody();
  }

  /**
   * Create an instance of
   * {@link UploadCollectionOrderBatchRequest.Body.CollectionOrderTerminations.CollectionOrderTermination }
   * 
   */
  public UploadCollectionOrderBatchRequest.Body.CollectionOrderTerminations.CollectionOrderTermination createUploadCollectionOrderBatchRequestBodyCollectionOrderTerminationsCollectionOrderTermination() {
    return new UploadCollectionOrderBatchRequest.Body.CollectionOrderTerminations.CollectionOrderTermination();
  }

}
