//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.13 at 01:16:05 PM CEST
//


package bindings.commons.automation.mule.model.mule.development.collection.aio.channel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for terminationType.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="terminationType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PRE_TERMINATION"/&gt;
 *     &lt;enumeration value="TERMINATION"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "terminationType")
@XmlEnum
public enum TerminationType {

  PRE_TERMINATION,
  TERMINATION;

  public String value() {
    return name();
  }

  public static TerminationType fromValue(final String v) {
    return valueOf(v);
  }

}
