//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.13 at 01:16:05 PM CEST
//


package bindings.commons.automation.mule.model.mule.development.collection.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://ipfdigital.com/Mule/Collection}headerType"/&gt;
 *         &lt;element name="collectionOrdersData"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="collectionOrderData" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                             &lt;element name="collectionOrderId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                             &lt;element name="collectionOrderDataBody" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
 *                                       &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="collectionCompanyId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="contractStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="collectionCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="personalDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="msisdn2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="address" type="{http://ipfdigital.com/Mule/Collection}addressType"/&gt;
 *                                       &lt;element name="correspondenceAddress" type="{http://ipfdigital.com/Mule/Collection}addressType" minOccurs="0"/&gt;
 *                                       &lt;element name="loansNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="employmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="bankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="loanSum" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="provisioningFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="invoiceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="firstDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                                       &lt;element name="contractInterest" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="maturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="terminationNoticeDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="contractTerminationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="moneyReceivedBeforeCollection" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="remainingMaturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="lastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                                       &lt;element name="lastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *                                       &lt;element name="totalOutstandingAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="totalBalancePrincipal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="totalBalanceFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="totalBalanceInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                       &lt;element name="totalBalanceLateInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "collectionOrdersData"
})
@XmlRootElement(name = "uploadCollectionOrderToSellBatchRequest")
public class UploadCollectionOrderToSellBatchRequest {

  @XmlElement(required = true)
  protected HeaderType header;
  @XmlElement(required = true)
  protected CollectionOrdersData collectionOrdersData;

  /**
   * Gets the value of the header property.
   *
   * @return possible object is {@link HeaderType }
   *
   */
  public HeaderType getHeader() {
    return this.header;
  }

  /**
   * Sets the value of the header property.
   *
   * @param value allowed object is {@link HeaderType }
   *
   */
  public void setHeader(final HeaderType value) {
    this.header = value;
  }

  /**
   * Gets the value of the collectionOrdersData property.
   *
   * @return possible object is
   *         {@link CollectionOrdersData }
   *
   */
  public CollectionOrdersData getCollectionOrdersData() {
    return this.collectionOrdersData;
  }

  /**
   * Sets the value of the collectionOrdersData property.
   *
   * @param value allowed object is
   *        {@link CollectionOrdersData }
   *
   */
  public void setCollectionOrdersData(
      final CollectionOrdersData value) {
    this.collectionOrdersData = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   *
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="collectionOrderData" maxOccurs="unbounded" minOccurs="0"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
   *                   &lt;element name="collectionOrderId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                   &lt;element name="collectionOrderDataBody" minOccurs="0"&gt;
   *                     &lt;complexType&gt;
   *                       &lt;complexContent&gt;
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                           &lt;sequence&gt;
   *                             &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
   *                             &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="collectionCompanyId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="contractStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
   *                             &lt;element name="collectionCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="personalDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="msisdn2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                             &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="address" type="{http://ipfdigital.com/Mule/Collection}addressType"/&gt;
   *                             &lt;element name="correspondenceAddress" type="{http://ipfdigital.com/Mule/Collection}addressType" minOccurs="0"/&gt;
   *                             &lt;element name="loansNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
   *                             &lt;element name="employmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                             &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                             &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="bankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="loanSum" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="provisioningFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="invoiceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="firstDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
   *                             &lt;element name="contractInterest" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="maturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
   *                             &lt;element name="terminationNoticeDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
   *                             &lt;element name="contractTerminationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
   *                             &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="moneyReceivedBeforeCollection" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="remainingMaturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
   *                             &lt;element name="lastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
   *                             &lt;element name="lastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
   *                             &lt;element name="totalOutstandingAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="totalBalancePrincipal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="totalBalanceFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="totalBalanceInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                             &lt;element name="totalBalanceLateInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
   *                           &lt;/sequence&gt;
   *                         &lt;/restriction&gt;
   *                       &lt;/complexContent&gt;
   *                     &lt;/complexType&gt;
   *                   &lt;/element&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   *
   *
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "collectionOrderData"
  })
  public static class CollectionOrdersData {

    @XmlElement(nillable = true)
    private List<CollectionOrderData> collectionOrderData;

    /**
     * Gets the value of the collectionOrderData property.
     *
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the collectionOrderData property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     *
     * <pre>
     * getCollectionOrderData().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CollectionOrderData }
     *
     *
     */
    public List<CollectionOrderData> getCollectionOrderData() {
      if (this.collectionOrderData == null) {
        this.collectionOrderData = new ArrayList<>();
      }
      return this.collectionOrderData;
    }

    public void setCollectionOrderData(final List<CollectionOrderData> collectionOrderData) {
      this.collectionOrderData = collectionOrderData;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="success" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="collectionOrderId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *         &lt;element name="collectionOrderDataBody" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
     *                   &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="collectionCompanyId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="contractStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="collectionCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="personalDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="msisdn2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="address" type="{http://ipfdigital.com/Mule/Collection}addressType"/&gt;
     *                   &lt;element name="correspondenceAddress" type="{http://ipfdigital.com/Mule/Collection}addressType" minOccurs="0"/&gt;
     *                   &lt;element name="loansNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="employmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="bankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="loanSum" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="provisioningFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="invoiceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="firstDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="contractInterest" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="maturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="terminationNoticeDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="contractTerminationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="moneyReceivedBeforeCollection" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="remainingMaturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="lastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="lastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
     *                   &lt;element name="totalOutstandingAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="totalBalancePrincipal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="totalBalanceFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="totalBalanceInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                   &lt;element name="totalBalanceLateInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "success",
        "collectionOrderId",
        "collectionOrderDataBody"
    })
    public static class CollectionOrderData {

      protected boolean success;
      protected long collectionOrderId;
      protected CollectionOrderDataBody collectionOrderDataBody;

      /**
       * Gets the value of the success property.
       *
       */
      public boolean isSuccess() {
        return this.success;
      }

      /**
       * Sets the value of the success property.
       *
       */
      public void setSuccess(final boolean value) {
        this.success = value;
      }

      /**
       * Gets the value of the collectionOrderId property.
       *
       */
      public long getCollectionOrderId() {
        return this.collectionOrderId;
      }

      /**
       * Sets the value of the collectionOrderId property.
       *
       */
      public void setCollectionOrderId(final long value) {
        this.collectionOrderId = value;
      }

      /**
       * Gets the value of the collectionOrderDataBody property.
       *
       * @return possible object is
       *         {@link CollectionOrderDataBody }
       *
       */
      public CollectionOrderDataBody getCollectionOrderDataBody() {
        return this.collectionOrderDataBody;
      }

      /**
       * Sets the value of the collectionOrderDataBody property.
       *
       * @param value allowed object is
       *        {@link CollectionOrderDataBody }
       *
       */
      public void setCollectionOrderDataBody(
          final CollectionOrderDataBody value) {
        this.collectionOrderDataBody = value;
      }


      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType&gt;
       *   &lt;complexContent&gt;
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
       *       &lt;sequence&gt;
       *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/&gt;
       *         &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="collectionCompanyId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="contractStartDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
       *         &lt;element name="collectionCompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="ssn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="personalDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="msisdn2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
       *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
       *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="address" type="{http://ipfdigital.com/Mule/Collection}addressType"/&gt;
       *         &lt;element name="correspondenceAddress" type="{http://ipfdigital.com/Mule/Collection}addressType" minOccurs="0"/&gt;
       *         &lt;element name="loansNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
       *         &lt;element name="employmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
       *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
       *         &lt;element name="income" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="bankAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="brand" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="channel" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="loanSum" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="provisioningFeeAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="invoiceAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="firstDueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
       *         &lt;element name="contractInterest" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="maturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
       *         &lt;element name="terminationNoticeDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
       *         &lt;element name="contractTerminationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
       *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="moneyReceivedBeforeCollection" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="remainingMaturity" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
       *         &lt;element name="lastPaymentDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
       *         &lt;element name="lastPaymentAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
       *         &lt;element name="totalOutstandingAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="totalBalancePrincipal" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="totalBalanceFees" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="totalBalanceInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *         &lt;element name="totalBalanceLateInterests" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
       *       &lt;/sequence&gt;
       *     &lt;/restriction&gt;
       *   &lt;/complexContent&gt;
       * &lt;/complexType&gt;
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = {
          "customerId",
          "contractId",
          "contractIdentity",
          "creditApplicationId",
          "collectionCompanyId",
          "contractStartDate",
          "collectionCompanyName",
          "ssn",
          "msisdn",
          "personalDocumentNumber",
          "msisdn2",
          "email",
          "firstName",
          "lastName",
          "address",
          "correspondenceAddress",
          "loansNumber",
          "employmentStatus",
          "company",
          "income",
          "bankAccount",
          "brand",
          "channel",
          "type",
          "loanSum",
          "provisioningFeeAmount",
          "invoiceAmount",
          "firstDueDate",
          "contractInterest",
          "maturity",
          "terminationNoticeDate",
          "contractTerminationDate",
          "level",
          "moneyReceivedBeforeCollection",
          "remainingMaturity",
          "lastPaymentDate",
          "lastPaymentAmount",
          "totalOutstandingAmount",
          "totalBalancePrincipal",
          "totalBalanceFees",
          "totalBalanceInterests",
          "totalBalanceLateInterests"
      })
      public static class CollectionOrderDataBody {

        protected long customerId;
        protected long contractId;
        protected Long contractIdentity;
        protected long creditApplicationId;
        protected long collectionCompanyId;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractStartDate;
        @XmlElement(required = true)
        protected String collectionCompanyName;
        @XmlElement(required = true)
        protected String ssn;
        @XmlElement(required = true)
        protected String msisdn;
        @XmlElement(required = true)
        protected String personalDocumentNumber;
        protected String msisdn2;
        protected String email;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected AddressType address;
        protected AddressType correspondenceAddress;
        protected int loansNumber;
        protected String employmentStatus;
        protected String company;
        @XmlElement(required = true)
        protected BigDecimal income;
        @XmlElement(required = true)
        protected String bankAccount;
        @XmlElement(required = true)
        protected String brand;
        @XmlElement(required = true)
        protected String channel;
        @XmlElement(required = true)
        protected String type;
        @XmlElement(required = true)
        protected BigDecimal loanSum;
        @XmlElement(required = true)
        protected BigDecimal provisioningFeeAmount;
        @XmlElement(required = true)
        protected BigDecimal invoiceAmount;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar firstDueDate;
        @XmlElement(required = true)
        protected BigDecimal contractInterest;
        protected int maturity;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar terminationNoticeDate;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractTerminationDate;
        @XmlElement(required = true)
        protected String level;
        @XmlElement(required = true)
        protected BigDecimal moneyReceivedBeforeCollection;
        protected int remainingMaturity;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar lastPaymentDate;
        protected BigDecimal lastPaymentAmount;
        @XmlElement(required = true)
        protected BigDecimal totalOutstandingAmount;
        @XmlElement(required = true)
        protected BigDecimal totalBalancePrincipal;
        @XmlElement(required = true)
        protected BigDecimal totalBalanceFees;
        @XmlElement(required = true)
        protected BigDecimal totalBalanceInterests;
        @XmlElement(required = true)
        protected BigDecimal totalBalanceLateInterests;

        /**
         * Gets the value of the customerId property.
         * 
         */
        public long getCustomerId() {
          return this.customerId;
        }

        /**
         * Sets the value of the customerId property.
         * 
         */
        public void setCustomerId(final long value) {
          this.customerId = value;
        }

        /**
         * Gets the value of the contractId property.
         * 
         */
        public long getContractId() {
          return this.contractId;
        }

        /**
         * Sets the value of the contractId property.
         * 
         */
        public void setContractId(final long value) {
          this.contractId = value;
        }

        /**
         * Gets the value of the contractIdentity property.
         * 
         * @return possible object is {@link Long }
         * 
         */
        public Long getContractIdentity() {
          return this.contractIdentity;
        }

        /**
         * Sets the value of the contractIdentity property.
         * 
         * @param value allowed object is {@link Long }
         * 
         */
        public void setContractIdentity(final Long value) {
          this.contractIdentity = value;
        }

        /**
         * Gets the value of the creditApplicationId property.
         * 
         */
        public long getCreditApplicationId() {
          return this.creditApplicationId;
        }

        /**
         * Sets the value of the creditApplicationId property.
         * 
         */
        public void setCreditApplicationId(final long value) {
          this.creditApplicationId = value;
        }

        /**
         * Gets the value of the collectionCompanyId property.
         * 
         */
        public long getCollectionCompanyId() {
          return this.collectionCompanyId;
        }

        /**
         * Sets the value of the collectionCompanyId property.
         * 
         */
        public void setCollectionCompanyId(final long value) {
          this.collectionCompanyId = value;
        }

        /**
         * Gets the value of the contractStartDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getContractStartDate() {
          return this.contractStartDate;
        }

        /**
         * Sets the value of the contractStartDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setContractStartDate(final XMLGregorianCalendar value) {
          this.contractStartDate = value;
        }

        /**
         * Gets the value of the collectionCompanyName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCollectionCompanyName() {
          return this.collectionCompanyName;
        }

        /**
         * Sets the value of the collectionCompanyName property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCollectionCompanyName(final String value) {
          this.collectionCompanyName = value;
        }

        /**
         * Gets the value of the ssn property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getSsn() {
          return this.ssn;
        }

        /**
         * Sets the value of the ssn property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setSsn(final String value) {
          this.ssn = value;
        }

        /**
         * Gets the value of the msisdn property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getMsisdn() {
          return this.msisdn;
        }

        /**
         * Sets the value of the msisdn property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setMsisdn(final String value) {
          this.msisdn = value;
        }

        /**
         * Gets the value of the personalDocumentNumber property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPersonalDocumentNumber() {
          return this.personalDocumentNumber;
        }

        /**
         * Sets the value of the personalDocumentNumber property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setPersonalDocumentNumber(final String value) {
          this.personalDocumentNumber = value;
        }

        /**
         * Gets the value of the msisdn2 property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getMsisdn2() {
          return this.msisdn2;
        }

        /**
         * Sets the value of the msisdn2 property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setMsisdn2(final String value) {
          this.msisdn2 = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getEmail() {
          return this.email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setEmail(final String value) {
          this.email = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getFirstName() {
          return this.firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setFirstName(final String value) {
          this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLastName() {
          return this.lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLastName(final String value) {
          this.lastName = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return possible object is {@link AddressType }
         * 
         */
        public AddressType getAddress() {
          return this.address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value allowed object is {@link AddressType }
         * 
         */
        public void setAddress(final AddressType value) {
          this.address = value;
        }

        /**
         * Gets the value of the correspondenceAddress property.
         * 
         * @return possible object is {@link AddressType }
         * 
         */
        public AddressType getCorrespondenceAddress() {
          return this.correspondenceAddress;
        }

        /**
         * Sets the value of the correspondenceAddress property.
         * 
         * @param value allowed object is {@link AddressType }
         * 
         */
        public void setCorrespondenceAddress(final AddressType value) {
          this.correspondenceAddress = value;
        }

        /**
         * Gets the value of the loansNumber property.
         * 
         */
        public int getLoansNumber() {
          return this.loansNumber;
        }

        /**
         * Sets the value of the loansNumber property.
         * 
         */
        public void setLoansNumber(final int value) {
          this.loansNumber = value;
        }

        /**
         * Gets the value of the employmentStatus property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getEmploymentStatus() {
          return this.employmentStatus;
        }

        /**
         * Sets the value of the employmentStatus property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setEmploymentStatus(final String value) {
          this.employmentStatus = value;
        }

        /**
         * Gets the value of the company property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCompany() {
          return this.company;
        }

        /**
         * Sets the value of the company property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCompany(final String value) {
          this.company = value;
        }

        /**
         * Gets the value of the income property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getIncome() {
          return this.income;
        }

        /**
         * Sets the value of the income property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setIncome(final BigDecimal value) {
          this.income = value;
        }

        /**
         * Gets the value of the bankAccount property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBankAccount() {
          return this.bankAccount;
        }

        /**
         * Sets the value of the bankAccount property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setBankAccount(final String value) {
          this.bankAccount = value;
        }

        /**
         * Gets the value of the brand property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getBrand() {
          return this.brand;
        }

        /**
         * Sets the value of the brand property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setBrand(final String value) {
          this.brand = value;
        }

        /**
         * Gets the value of the channel property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getChannel() {
          return this.channel;
        }

        /**
         * Sets the value of the channel property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setChannel(final String value) {
          this.channel = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getType() {
          return this.type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setType(final String value) {
          this.type = value;
        }

        /**
         * Gets the value of the loanSum property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getLoanSum() {
          return this.loanSum;
        }

        /**
         * Sets the value of the loanSum property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setLoanSum(final BigDecimal value) {
          this.loanSum = value;
        }

        /**
         * Gets the value of the provisioningFeeAmount property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getProvisioningFeeAmount() {
          return this.provisioningFeeAmount;
        }

        /**
         * Sets the value of the provisioningFeeAmount property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setProvisioningFeeAmount(final BigDecimal value) {
          this.provisioningFeeAmount = value;
        }

        /**
         * Gets the value of the invoiceAmount property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getInvoiceAmount() {
          return this.invoiceAmount;
        }

        /**
         * Sets the value of the invoiceAmount property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setInvoiceAmount(final BigDecimal value) {
          this.invoiceAmount = value;
        }

        /**
         * Gets the value of the firstDueDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getFirstDueDate() {
          return this.firstDueDate;
        }

        /**
         * Sets the value of the firstDueDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setFirstDueDate(final XMLGregorianCalendar value) {
          this.firstDueDate = value;
        }

        /**
         * Gets the value of the contractInterest property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getContractInterest() {
          return this.contractInterest;
        }

        /**
         * Sets the value of the contractInterest property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setContractInterest(final BigDecimal value) {
          this.contractInterest = value;
        }

        /**
         * Gets the value of the maturity property.
         * 
         */
        public int getMaturity() {
          return this.maturity;
        }

        /**
         * Sets the value of the maturity property.
         * 
         */
        public void setMaturity(final int value) {
          this.maturity = value;
        }

        /**
         * Gets the value of the terminationNoticeDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getTerminationNoticeDate() {
          return this.terminationNoticeDate;
        }

        /**
         * Sets the value of the terminationNoticeDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setTerminationNoticeDate(final XMLGregorianCalendar value) {
          this.terminationNoticeDate = value;
        }

        /**
         * Gets the value of the contractTerminationDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getContractTerminationDate() {
          return this.contractTerminationDate;
        }

        /**
         * Sets the value of the contractTerminationDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setContractTerminationDate(final XMLGregorianCalendar value) {
          this.contractTerminationDate = value;
        }

        /**
         * Gets the value of the level property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLevel() {
          return this.level;
        }

        /**
         * Sets the value of the level property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLevel(final String value) {
          this.level = value;
        }

        /**
         * Gets the value of the moneyReceivedBeforeCollection property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getMoneyReceivedBeforeCollection() {
          return this.moneyReceivedBeforeCollection;
        }

        /**
         * Sets the value of the moneyReceivedBeforeCollection property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setMoneyReceivedBeforeCollection(final BigDecimal value) {
          this.moneyReceivedBeforeCollection = value;
        }

        /**
         * Gets the value of the remainingMaturity property.
         * 
         */
        public int getRemainingMaturity() {
          return this.remainingMaturity;
        }

        /**
         * Sets the value of the remainingMaturity property.
         * 
         */
        public void setRemainingMaturity(final int value) {
          this.remainingMaturity = value;
        }

        /**
         * Gets the value of the lastPaymentDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getLastPaymentDate() {
          return this.lastPaymentDate;
        }

        /**
         * Sets the value of the lastPaymentDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setLastPaymentDate(final XMLGregorianCalendar value) {
          this.lastPaymentDate = value;
        }

        /**
         * Gets the value of the lastPaymentAmount property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getLastPaymentAmount() {
          return this.lastPaymentAmount;
        }

        /**
         * Sets the value of the lastPaymentAmount property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setLastPaymentAmount(final BigDecimal value) {
          this.lastPaymentAmount = value;
        }

        /**
         * Gets the value of the totalOutstandingAmount property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTotalOutstandingAmount() {
          return this.totalOutstandingAmount;
        }

        /**
         * Sets the value of the totalOutstandingAmount property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setTotalOutstandingAmount(final BigDecimal value) {
          this.totalOutstandingAmount = value;
        }

        /**
         * Gets the value of the totalBalancePrincipal property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTotalBalancePrincipal() {
          return this.totalBalancePrincipal;
        }

        /**
         * Sets the value of the totalBalancePrincipal property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setTotalBalancePrincipal(final BigDecimal value) {
          this.totalBalancePrincipal = value;
        }

        /**
         * Gets the value of the totalBalanceFees property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTotalBalanceFees() {
          return this.totalBalanceFees;
        }

        /**
         * Sets the value of the totalBalanceFees property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setTotalBalanceFees(final BigDecimal value) {
          this.totalBalanceFees = value;
        }

        /**
         * Gets the value of the totalBalanceInterests property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTotalBalanceInterests() {
          return this.totalBalanceInterests;
        }

        /**
         * Sets the value of the totalBalanceInterests property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setTotalBalanceInterests(final BigDecimal value) {
          this.totalBalanceInterests = value;
        }

        /**
         * Gets the value of the totalBalanceLateInterests property.
         * 
         * @return possible object is {@link BigDecimal }
         * 
         */
        public BigDecimal getTotalBalanceLateInterests() {
          return this.totalBalanceLateInterests;
        }

        /**
         * Sets the value of the totalBalanceLateInterests property.
         * 
         * @param value allowed object is {@link BigDecimal }
         * 
         */
        public void setTotalBalanceLateInterests(final BigDecimal value) {
          this.totalBalanceLateInterests = value;
        }

      }

    }

  }

}
