//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.13 at 01:16:05 PM CEST
//


package bindings.commons.automation.mule.model.mule.development.collection.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="header" type="{http://ipfdigital.com/Mule/Collection}headerType"/&gt;
 *         &lt;element name="body"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="collectionOrderTerminations"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="collectionOrderTermination" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *                                       &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *                                       &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="door" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                       &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                       &lt;element name="contractOpenDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *                                       &lt;element name="totalDueAmount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="repaymentIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="terminationType" type="{http://ipfdigital.com/Mule/Collection}terminationType"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "body"
})
@XmlRootElement(name = "uploadCollectionOrderBatchRequest")
public class UploadCollectionOrderBatchRequest {

  @XmlElement(required = true)
  protected HeaderType header;
  @XmlElement(required = true)
  protected Body body;

  /**
   * Gets the value of the header property.
   *
   * @return possible object is {@link HeaderType }
   *
   */
  public HeaderType getHeader() {
    return this.header;
  }

  /**
   * Sets the value of the header property.
   *
   * @param value allowed object is {@link HeaderType }
   *
   */
  public void setHeader(final HeaderType value) {
    this.header = value;
  }

  /**
   * Gets the value of the body property.
   *
   * @return possible object is {@link Body }
   *
   */
  public Body getBody() {
    return this.body;
  }

  /**
   * Sets the value of the body property.
   *
   * @param value allowed object is {@link Body }
   *
   */
  public void setBody(final Body value) {
    this.body = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   *
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="collectionOrderTerminations"&gt;
   *           &lt;complexType&gt;
   *             &lt;complexContent&gt;
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                 &lt;sequence&gt;
   *                   &lt;element name="collectionOrderTermination" maxOccurs="unbounded" minOccurs="0"&gt;
   *                     &lt;complexType&gt;
   *                       &lt;complexContent&gt;
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *                           &lt;sequence&gt;
   *                             &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
   *                             &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
   *                             &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="door" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                             &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                             &lt;element name="contractOpenDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
   *                             &lt;element name="totalDueAmount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
   *                             &lt;element name="repaymentIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *                           &lt;/sequence&gt;
   *                         &lt;/restriction&gt;
   *                       &lt;/complexContent&gt;
   *                     &lt;/complexType&gt;
   *                   &lt;/element&gt;
   *                   &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
   *                   &lt;element name="terminationType" type="{http://ipfdigital.com/Mule/Collection}terminationType"/&gt;
   *                 &lt;/sequence&gt;
   *               &lt;/restriction&gt;
   *             &lt;/complexContent&gt;
   *           &lt;/complexType&gt;
   *         &lt;/element&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   *
   *
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "collectionOrderTerminations"
  })
  public static class Body {

    @XmlElement(required = true)
    protected CollectionOrderTerminations collectionOrderTerminations;

    /**
     * Gets the value of the collectionOrderTerminations property.
     *
     * @return possible object is
     *         {@link CollectionOrderTerminations }
     *
     */
    public CollectionOrderTerminations getCollectionOrderTerminations() {
      return this.collectionOrderTerminations;
    }

    /**
     * Sets the value of the collectionOrderTerminations property.
     *
     * @param value allowed object is
     *        {@link CollectionOrderTerminations }
     *
     */
    public void setCollectionOrderTerminations(
        final CollectionOrderTerminations value) {
      this.collectionOrderTerminations = value;
    }


    /**
     * <p>
     * Java class for anonymous complex type.
     *
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="collectionOrderTermination" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
     *                   &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
     *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="door" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="contractOpenDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
     *                   &lt;element name="totalDueAmount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="repaymentIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="fileName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="terminationType" type="{http://ipfdigital.com/Mule/Collection}terminationType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "collectionOrderTermination",
        "fileName",
        "terminationType"
    })
    public static class CollectionOrderTerminations {

      @XmlElement(nillable = true)
      private List<CollectionOrderTermination> collectionOrderTermination;
      @XmlElement(required = true)
      protected String fileName;
      @XmlElement(required = true)
      @XmlSchemaType(name = "string")
      protected TerminationType terminationType;

      /**
       * Gets the value of the collectionOrderTermination property.
       *
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any
       * modification you make to the returned list will be present inside the JAXB object. This is
       * why there is not a <CODE>set</CODE> method for the collectionOrderTermination property.
       *
       * <p>
       * For example, to add a new item, do as follows:
       *
       * <pre>
       * getCollectionOrderTermination().add(newItem);
       * </pre>
       *
       *
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link CollectionOrderTermination }
       *
       *
       */
      public List<CollectionOrderTermination> getCollectionOrderTermination() {
        if (this.collectionOrderTermination == null) {
          this.collectionOrderTermination = new ArrayList<>();
        }
        return this.collectionOrderTermination;
      }

      /**
       * Gets the value of the fileName property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getFileName() {
        return this.fileName;
      }

      /**
       * Sets the value of the fileName property.
       * 
       * @param value allowed object is {@link String }
       * 
       */
      public void setFileName(final String value) {
        this.fileName = value;
      }

      /**
       * Gets the value of the terminationType property.
       * 
       * @return possible object is {@link TerminationType }
       * 
       */
      public TerminationType getTerminationType() {
        return this.terminationType;
      }

      /**
       * Sets the value of the terminationType property.
       * 
       * @param value allowed object is {@link TerminationType }
       * 
       */
      public void setTerminationType(final TerminationType value) {
        this.terminationType = value;
      }

      public void setCollectionOrderTermination(
          final List<CollectionOrderTermination> collectionOrderTermination) {
        this.collectionOrderTermination = collectionOrderTermination;
      }


      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType&gt;
       *   &lt;complexContent&gt;
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
       *       &lt;sequence&gt;
       *         &lt;element name="customerId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="contractId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="creditApplicationId" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
       *         &lt;element name="generationDate" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
       *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="door" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
       *         &lt;element name="street" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="contractIdentity" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
       *         &lt;element name="contractOpenDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
       *         &lt;element name="totalDueAmount" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
       *         &lt;element name="repaymentIBAN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
       *       &lt;/sequence&gt;
       *     &lt;/restriction&gt;
       *   &lt;/complexContent&gt;
       * &lt;/complexType&gt;
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = {
          "customerId",
          "contractId",
          "creditApplicationId",
          "generationDate",
          "firstName",
          "lastName",
          "door",
          "street",
          "postcode",
          "city",
          "contractIdentity",
          "contractOpenDate",
          "totalDueAmount",
          "repaymentIBAN"
      })
      public static class CollectionOrderTermination {

        protected long customerId;
        protected long contractId;
        protected long creditApplicationId;
        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar generationDate;
        @XmlElement(required = true)
        protected String firstName;
        @XmlElement(required = true)
        protected String lastName;
        protected String door;
        @XmlElement(required = true)
        protected String street;
        @XmlElement(required = true)
        protected String postcode;
        @XmlElement(required = true)
        protected String city;
        @XmlElement(required = true)
        protected String contractIdentity;
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar contractOpenDate;
        protected int totalDueAmount;
        protected String repaymentIBAN;

        /**
         * Gets the value of the customerId property.
         * 
         */
        public long getCustomerId() {
          return this.customerId;
        }

        /**
         * Sets the value of the customerId property.
         * 
         */
        public void setCustomerId(final long value) {
          this.customerId = value;
        }

        /**
         * Gets the value of the contractId property.
         * 
         */
        public long getContractId() {
          return this.contractId;
        }

        /**
         * Sets the value of the contractId property.
         * 
         */
        public void setContractId(final long value) {
          this.contractId = value;
        }

        /**
         * Gets the value of the creditApplicationId property.
         * 
         */
        public long getCreditApplicationId() {
          return this.creditApplicationId;
        }

        /**
         * Sets the value of the creditApplicationId property.
         * 
         */
        public void setCreditApplicationId(final long value) {
          this.creditApplicationId = value;
        }

        /**
         * Gets the value of the generationDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getGenerationDate() {
          return this.generationDate;
        }

        /**
         * Sets the value of the generationDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setGenerationDate(final XMLGregorianCalendar value) {
          this.generationDate = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getFirstName() {
          return this.firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setFirstName(final String value) {
          this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLastName() {
          return this.lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setLastName(final String value) {
          this.lastName = value;
        }

        /**
         * Gets the value of the door property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getDoor() {
          return this.door;
        }

        /**
         * Sets the value of the door property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setDoor(final String value) {
          this.door = value;
        }

        /**
         * Gets the value of the street property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getStreet() {
          return this.street;
        }

        /**
         * Sets the value of the street property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setStreet(final String value) {
          this.street = value;
        }

        /**
         * Gets the value of the postcode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getPostcode() {
          return this.postcode;
        }

        /**
         * Sets the value of the postcode property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setPostcode(final String value) {
          this.postcode = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCity() {
          return this.city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setCity(final String value) {
          this.city = value;
        }

        /**
         * Gets the value of the contractIdentity property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getContractIdentity() {
          return this.contractIdentity;
        }

        /**
         * Sets the value of the contractIdentity property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setContractIdentity(final String value) {
          this.contractIdentity = value;
        }

        /**
         * Gets the value of the contractOpenDate property.
         * 
         * @return possible object is {@link XMLGregorianCalendar }
         * 
         */
        public XMLGregorianCalendar getContractOpenDate() {
          return this.contractOpenDate;
        }

        /**
         * Sets the value of the contractOpenDate property.
         * 
         * @param value allowed object is {@link XMLGregorianCalendar }
         * 
         */
        public void setContractOpenDate(final XMLGregorianCalendar value) {
          this.contractOpenDate = value;
        }

        /**
         * Gets the value of the totalDueAmount property.
         * 
         */
        public int getTotalDueAmount() {
          return this.totalDueAmount;
        }

        /**
         * Sets the value of the totalDueAmount property.
         * 
         */
        public void setTotalDueAmount(final int value) {
          this.totalDueAmount = value;
        }

        /**
         * Gets the value of the repaymentIBAN property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getRepaymentIBAN() {
          return this.repaymentIBAN;
        }

        /**
         * Sets the value of the repaymentIBAN property.
         * 
         * @param value allowed object is {@link String }
         * 
         */
        public void setRepaymentIBAN(final String value) {
          this.repaymentIBAN = value;
        }

      }

    }

  }

}
