//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.07 at 02:57:37 PM CET
//


package bindings.commons.automation.mule.model.mule.development.customer.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseStatus" type="{http://ipfdigital.com/Mule/Customer/Channel}StatusResponseType"/&gt;
 *         &lt;element name="Body" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="IsNumberCorrect" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="BlueMediaSupport" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseStatus",
    "body"
})
@XmlRootElement(name = "CheckBankResponse")
public class CheckBankResponse {

  @XmlElement(name = "ResponseStatus", required = true)
  protected StatusResponseType responseStatus;
  @XmlElement(name = "Body")
  protected Body body;

  /**
   * Gets the value of the responseStatus property.
   *
   * @return possible object is {@link StatusResponseType }
   *
   */
  public StatusResponseType getResponseStatus() {
    return this.responseStatus;
  }

  /**
   * Sets the value of the responseStatus property.
   *
   * @param value allowed object is {@link StatusResponseType }
   *
   */
  public void setResponseStatus(final StatusResponseType value) {
    this.responseStatus = value;
  }

  /**
   * Gets the value of the body property.
   *
   * @return possible object is {@link Body }
   *
   */
  public Body getBody() {
    return this.body;
  }

  /**
   * Sets the value of the body property.
   *
   * @param value allowed object is {@link Body }
   *
   */
  public void setBody(final Body value) {
    this.body = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="IsNumberCorrect" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
   *         &lt;element name="BlueMediaSupport" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
   *         &lt;element name="BankName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "isNumberCorrect",
      "blueMediaSupport",
      "bankName"
  })
  public static class Body {

    @XmlElement(name = "IsNumberCorrect")
    protected boolean isNumberCorrect;
    @XmlElement(name = "BlueMediaSupport")
    protected boolean blueMediaSupport;
    @XmlElement(name = "BankName")
    protected String bankName;

    /**
     * Gets the value of the isNumberCorrect property.
     * 
     */
    public boolean isIsNumberCorrect() {
      return this.isNumberCorrect;
    }

    /**
     * Sets the value of the isNumberCorrect property.
     * 
     */
    public void setIsNumberCorrect(final boolean value) {
      this.isNumberCorrect = value;
    }

    /**
     * Gets the value of the blueMediaSupport property.
     * 
     */
    public boolean isBlueMediaSupport() {
      return this.blueMediaSupport;
    }

    /**
     * Sets the value of the blueMediaSupport property.
     * 
     */
    public void setBlueMediaSupport(final boolean value) {
      this.blueMediaSupport = value;
    }

    /**
     * Gets the value of the bankName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getBankName() {
      return this.bankName;
    }

    /**
     * Sets the value of the bankName property.
     * 
     * @param value allowed object is {@link String }
     * 
     */
    public void setBankName(final String value) {
      this.bankName = value;
    }

  }

}
