//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.07 at 02:57:37 PM CET
//


package bindings.commons.automation.mule.model.mule.development.customer.aio.channel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ipfdigital.automation.mule.model.mule.development.customer.aio.channel
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.ipfdigital.automation.mule.model.mule.development.customer.aio.channel
   * 
   */
  public ObjectFactory() {
    // New ObjectFactory
  }

  /**
   * Create an instance of {@link CheckBankRequest }
   * 
   */
  public CheckBankRequest createCheckBankRequest() {
    return new CheckBankRequest();
  }

  /**
   * Create an instance of {@link CheckBankResponse }
   * 
   */
  public CheckBankResponse createCheckBankResponse() {
    return new CheckBankResponse();
  }

  /**
   * Create an instance of {@link GetTmxSessionIdRequest }
   * 
   */
  public GetTmxSessionIdRequest createGetTmxSessionIdRequest() {
    return new GetTmxSessionIdRequest();
  }

  /**
   * Create an instance of {@link GetTmxSessionIdResponse }
   * 
   */
  public GetTmxSessionIdResponse createGetTmxSessionIdResponse() {
    return new GetTmxSessionIdResponse();
  }

  /**
   * Create an instance of {@link SearchForActiveLegacyCustomerDataResponse }
   * 
   */
  public SearchForActiveLegacyCustomerDataResponse createSearchForActiveLegacyCustomerDataResponse() {
    return new SearchForActiveLegacyCustomerDataResponse();
  }

  /**
   * Create an instance of {@link CheckBankRequest.Body }
   * 
   */
  public CheckBankRequest.Body createCheckBankRequestBody() {
    return new CheckBankRequest.Body();
  }

  /**
   * Create an instance of {@link StatusResponseType }
   * 
   */
  public StatusResponseType createStatusResponseType() {
    return new StatusResponseType();
  }

  /**
   * Create an instance of {@link CheckBankResponse.Body }
   * 
   */
  public CheckBankResponse.Body createCheckBankResponseBody() {
    return new CheckBankResponse.Body();
  }

  /**
   * Create an instance of {@link GetTmxSessionIdRequest.Body }
   * 
   */
  public GetTmxSessionIdRequest.Body createGetTmxSessionIdRequestBody() {
    return new GetTmxSessionIdRequest.Body();
  }

  /**
   * Create an instance of {@link GetTmxSessionIdResponse.Body }
   * 
   */
  public GetTmxSessionIdResponse.Body createGetTmxSessionIdResponseBody() {
    return new GetTmxSessionIdResponse.Body();
  }

  /**
   * Create an instance of {@link SearchForActiveLegacyCustomerDataRequest }
   * 
   */
  public SearchForActiveLegacyCustomerDataRequest createSearchForActiveLegacyCustomerDataRequest() {
    return new SearchForActiveLegacyCustomerDataRequest();
  }

  /**
   * Create an instance of {@link SearchForActiveLegacyCustomerDataResponse.Body }
   * 
   */
  public SearchForActiveLegacyCustomerDataResponse.Body createSearchForActiveLegacyCustomerDataResponseBody() {
    return new SearchForActiveLegacyCustomerDataResponse.Body();
  }

}
