//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.07 at 02:57:37 PM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ipfdigital.com/Mule/Customer/Channel")
package bindings.commons.automation.mule.model.mule.development.customer.aio.channel;
