//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.07 at 02:57:37 PM CET
//


package bindings.commons.automation.mule.model.mule.development.customer.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "email",
    "msisdn",
    "lastName",
    "dateOfBirth"
})
@XmlRootElement(name = "SearchForActiveLegacyCustomerDataRequest")
public class SearchForActiveLegacyCustomerDataRequest {

  protected String email;
  protected String msisdn;
  protected String lastName;
  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar dateOfBirth;

  /**
   * Gets the value of the email property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getEmail() {
    return this.email;
  }

  /**
   * Sets the value of the email property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setEmail(final String value) {
    this.email = value;
  }

  /**
   * Gets the value of the msisdn property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getMsisdn() {
    return this.msisdn;
  }

  /**
   * Sets the value of the msisdn property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setMsisdn(final String value) {
    this.msisdn = value;
  }

  /**
   * Gets the value of the lastName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getLastName() {
    return this.lastName;
  }

  /**
   * Sets the value of the lastName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setLastName(final String value) {
    this.lastName = value;
  }

  /**
   * Gets the value of the dateOfBirth property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getDateOfBirth() {
    return this.dateOfBirth;
  }

  /**
   * Sets the value of the dateOfBirth property.
   * 
   * @param value allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setDateOfBirth(final XMLGregorianCalendar value) {
    this.dateOfBirth = value;
  }

}
