//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.07 at 02:57:37 PM CET
//


package bindings.commons.automation.mule.model.mule.development.customer.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="responseStatus" type="{http://ipfdigital.com/Mule/Customer/Channel}StatusResponseType"/&gt;
 *         &lt;element name="body" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="customerFound" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="data" type="{http://ipfdigital.com/Mule/Customer/Channel}CustomerDataType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseStatus",
    "body"
})
@XmlRootElement(name = "SearchForActiveLegacyCustomerDataResponse")
public class SearchForActiveLegacyCustomerDataResponse {

  @XmlElement(required = true)
  protected StatusResponseType responseStatus;
  protected Body body;

  /**
   * Gets the value of the responseStatus property.
   *
   * @return possible object is {@link StatusResponseType }
   *
   */
  public StatusResponseType getResponseStatus() {
    return this.responseStatus;
  }

  /**
   * Sets the value of the responseStatus property.
   *
   * @param value allowed object is {@link StatusResponseType }
   *
   */
  public void setResponseStatus(final StatusResponseType value) {
    this.responseStatus = value;
  }

  /**
   * Gets the value of the body property.
   *
   * @return possible object is {@link Body }
   *
   */
  public Body getBody() {
    return this.body;
  }

  /**
   * Sets the value of the body property.
   *
   * @param value allowed object is {@link Body }
   *
   */
  public void setBody(final Body value) {
    this.body = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="customerFound" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
   *         &lt;element name="data" type="{http://ipfdigital.com/Mule/Customer/Channel}CustomerDataType"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "customerFound",
      "data"
  })
  public static class Body {

    protected boolean customerFound;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CustomerDataType data;

    /**
     * Gets the value of the customerFound property.
     * 
     */
    public boolean isCustomerFound() {
      return this.customerFound;
    }

    /**
     * Sets the value of the customerFound property.
     * 
     */
    public void setCustomerFound(final boolean value) {
      this.customerFound = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return possible object is {@link CustomerDataType }
     * 
     */
    public CustomerDataType getData() {
      return this.data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value allowed object is {@link CustomerDataType }
     * 
     */
    public void setData(final CustomerDataType value) {
      this.data = value;
    }

  }

}
