package bindings.commons.automation.customer.names;

import com.ipfdigital.automation.customer.Country;
import com.ipfdigital.automation.customer.Gender;
import com.ipfdigital.automation.generators.RandomUtils;

import java.util.Arrays;
import java.util.List;

final class ESNameGeneratorStrategy implements GenerateNameStrategy {

  private static final List<String> MALE_FIRST_NAMES = Arrays.asList(
      "Aarón", "Abel", "Abilio", "Abraha", "Adalberto", "Adán", "Adelardo", "Adolfito", "Adolfo",
      "Adrià",
      "Adrián", "Afonso", "Agapito", "Agustí", "Agustín", "Aingeru", "Aitor", "Albert", "Alberte",
      "Alberto",
      "Albino", "Alcides", "Ale", "Aleix", "Aleixo", "Alejandro", "Alejo", "Alesander", "àlex",
      "Alexandre",
      "Alfonso", "Alfredo", "Alvaro", "Amado", "Amancio", "Amando", "Ambrosio", "Américo",
      "Amets", "Amílcar", "Amor", "Anacleto", "Anastasio", "Ander", "Andoni", "Andreu", "ángel",
      "àngel", "Angelino", "Aníbal", "Anselmo", "Antelmo", "Antón", "Antoni", "Antonio", "Antton",
      "Anxo",
      "Apolinar", "Argi", "Argider", "Aristides", "Arkaitz", "Arnau", "Arrats", "Arsenio",
      "Artemio",
      "Artur", "Arturo", "Asdrubal", "Asier", "Atilio", "August", "Augusto", "Aureliano",
      "Aurelio", "Bakar",
      "Balbino", "Baldo", "Baldomero", "Balduino", "Balendin", "Baltasar", "Bartolomé",
      "Bartolomeu", "Bartomeu",
      "Basajaun", "Basilio", "Baudelio", "Beñat", "Benigno", "Benito", "Benjamín", "Berenguer",
      "Bermudo", "Bernardino", "Bernardo", "Bernat", "Berto", "Bieito", "Biel", "Bikendi",
      "Bittor", "Blas",
      "Bonifacio", "Brais", "Breixo", "Bruno", "Buenaventura", "Calisto", "Calixto", "Camilo",
      "Candelario", "Cándido", "Carles", "Carlito", "Carlitos", "Carlos", "Carmelo", "Casimiro",
      "Cayetano",
      "Cebrián", "Cecilio", "Ceferino", "Celestino", "Celino", "Celio", "Celso", "César", "Cesc",
      "Che", "Chimo",
      "Chucho", "Chus", "Chuy", "Cibrán", "Cipriano", "Ciríaco", "Ciriaco", "Cirino", "Ciro",
      "Claudio",
      "Clemente", "Cleto", "Clímaco", "Climent", "Conrado", "Cornelio", "Cristián", "Cristóbal",
      "Cruz", "Curro",
      "Custodio", "Dan", "Danel", "Dani", "Daniel", "Danilo", "Darío", "David", "Demetrio",
      "Desi", "Desiderio",
      "Dídac", "Diego", "Dimas", "Dionisio", "Domingo", "Donat", "Donato", "Duilio", "Eberardo",
      "Edelmiro",
      "Eder", "Edgardo", "Edmundo", "Edorta", "Eduard", "Eduardo", "Edur", "Efraín", "Eguzki",
      "Ekain", "Ekaitz",
      "Eladio", "Eleuterio", "Elías", "Eligio", "Eliseo", "Eloi", "Eloy", "Elpidio", "Emigdio",
      "Emiliano",
      "Emilio", "Endika", "Eneko", "Enric", "Enrique", "Epifanio", "Erasmo", "èric", "Eric",
      "Erlantz", "Ernesto",
      "Erramun", "Espiridión", "Estavan", "Esteban", "Estebe", "Esteve", "Estevo", "Eugenio",
      "Eusebio",
      "Eustaquio", "Eutimio", "Eutropio", "Evaristo", "Ezequiel", "Eztebe", "Fabián", "Fabio",
      "Fabricio",
      "Faustino", "Fausto", "Federico", "Feliciano", "Felip", "Felipe", "Feliu", "Fermín",
      "Fermin",
      "Fermintxo", "Fernando", "Ferran", "Fidel", "Fito", "Flavio", "Florencio", "Florentino",
      "Fortunato",
      "Fran", "Francesc", "Francisco", "Frantzisko", "Fulgencio", "Gabino", "Gabriel", "Gaizka",
      "Galo", "Ganix",
      "Garaile", "Gastón", "Geraldo", "Gerard", "Gerardo", "Germán", "Gerónimo", "Gervasio",
      "Gil",
      "Gilberto", "Glauco", "Godofredo", "Gonçal", "Gonzalo", "Gorka", "Gotzon", "Goyo",
      "Graciano", "Gregorio",
      "Gualterio", "Guifré", "Guille", "Guillermo", "Gurutz", "Gustavo", "Gutxi",
      "Harkaitz", "Haroldo", "Héctor", "Hèctor", "Heliodoro", "Heraclio", "Herberto", "Heriberto",
      "Hermenegildo",
      "Herminio", "Hernán", "Hernando", "Higini", "Hipólito", "Hodei", "Horacio", "Hugo", "Iago",
      "Ibai",
      "Ignacio", "Ignasi", "Igon", "Iker", "Ildefonso", "Imanol", "Iñaki", "íñigo", "Inocencio",
      "Ion", "Isaías",
      "Isidoro", "Isidro", "Ismael", "Itzal", "Iván", "Izotz", "Jacinto", "Jacobo", "Jafet",
      "Jaime", "Jakes",
      "Jan", "Jaume", "Jaumet", "Javier", "Jenaro", "Jeremías", "Jerónimo", "Jesús", "Jimeno",
      "Joan", "Joaqui",
      "Joaquín", "Joel", "Jofre", "Jokin", "Jon", "Jonatan", "Jordán", "Jordi", "Jorge", "José",
      "Joseba",
      "Josemaría", "Josep", "Josepe", "Josu", "Josué", "Juan", "Juanito", "Julen", "Julián",
      "Julio", "Kemen",
      "Kepa", "Kerman", "Kike", "Koldo", "Koldobika", "Lalo", "Lázaro", "Leandro", "Leocadio",
      "León", "Leonardo",
      "Leoncio", "Leopoldo", "Lino", "Lisandro", "Llorenç", "Lluc", "Lluís", "Lois", "Lope",
      "Lorenzo",
      "Lucas", "Lucho", "Luciano", "Lucio", "Luis", "Luken", "Lupe", "Macario", "Manel", "Manolo",
      "Manu",
      "Manuel", "Marc", "Marcel", "Marcelino", "Marcelo", "Marcial", "Marciano", "Marcio",
      "Marco", "Marcos",
      "Maria", "Mariano", "Mario", "Markel", "Marko", "Martí", "Martzel", "Mateo",
      "Mateu", "Matia", "Matías", "Mattin", "Matxin", "Mauricio", "Maximiano", "Maximiliano",
      "Maximino",
      "Máximo", "Melchor", "Miguel", "Miguelángel", "Miguelito", "Mikel", "Mintxo", "Miquel",
      "Mitxel", "Modesto",
      "Moisés", "Nacho", "Nacio", "Nando", "Narcís", "Narciso", "Natalio", "Natanael", "Nataniel",
      "Nazario",
      "Nico", "Nicodemo", "Nicolás", "Nicolau", "Nikola", "Noé", "Norberto", "Octavio", "Oier",
      "Olegario", "Onofre", "Orfeo", "Oriol", "Oroitz", "Ortzi", "óscar", "òscar", "Osvaldo",
      "Ovidio", "Pablo",
      "Paco", "Pancho", "Pánfilo", "Paquito", "Pascual", "Pastor", "Patricio", "Patxi", "Pau",
      "Paulino", "Paulo",
      "Pedro", "Peio", "Pepe", "Pepito", "Pere", "Peru", "Petri", "Pío", "Plácido", "Plinio",
      "Pol", "Poncio",
      "Porfirio", "Primitivo", "Próspero", "Prudencio", "Qui", "Quique", "Quirino", "Rafa",
      "Rafael", "Raimon",
      "Raimundo", "Rainerio", "Ramiro", "Ramón", "Ramon", "Raúl", "Raymundo", "Régulo",
      "Reinaldo", "Remigio",
      "Renato", "René", "Reynaldo", "Ricard", "Ricardo", "Rico", "Roberto", "Roc", "Roderic",
      "Rodolfito", "Rodolfo", "Rodrigo", "Rogelio", "Roger", "Roi", "Rolando", "Romà", "Román",
      "Roque",
      "Rosendo", "Rubén", "Rufino", "Ruperto", "Ruy", "Sabas", "Salomón", "Salvador", "Samuel",
      "Sancho", "Sandalio", "Saturnino", "Sebastián", "Sendoa", "Sergi", "Sergio", "Seve",
      "Severiano", "Severino", "Severo", "Sigfrido", "Silvestre", "Silvio", "Simón", "Sofronio",
      "Sosimo",
      "Tacito", "Tadeo", "Tancredo", "Telmo", "Teo", "Teobaldo", "Teodoro", "Teodosio", "Teódulo",
      "Teófilo",
      "Tercero", "Tiburcio", "Timoteo", "Tito", "Tomás", "Tomàs", "Toni", "Toño", "Toribio",
      "Tristán", "Tulio", "Txomin", "Ulises", "Unai", "Urbano", "Uxío", "Valentín", "Valerio",
      "Valero", "Vasco",
      "Venceslás", "Vicenç", "Vicent", "Vicente", "Víctor", "Victorino", "Vidal", "Vinicio",
      "Virgilio", "Vito",
      "Vítor", "Wilfredo", "Xabi", "Xabier", "Xanti", "Xavi", "Xavier", "Xesús", "Ximo", "Ximun",
      "Xoán", "Xoel",
      "Xosé", "Xuan", "Xurxo", "Yago", "Zacarías", "Zeru", "Zigor", "Zorion", "Zuzen");
  private static final List<String> FEMALE_FIRST_NAMES = Arrays.asList(
      "Abene", "Abigaíl", "Adela", "Adelaida", "Adelia", "Adelina", "Adelita", "Adora",
      "Adoración", "Adriana",
      "áfrica", "Agata", "Agnès", "águeda", "Agurne", "Agurtzane", "Agustina", "Aina", "Ainhoa",
      "Ainoa",
      "Aintza", "Aintzane", "Alaia", "Alazne", "Alba", "Albina", "Ale", "Alejandra", "Alexandra",
      "Alícia",
      "Alicia", "Alma", "Almudena", "Alondra", "Amada", "Amaia", "Amalia", "Amanda", "Amaranta",
      "Amarilis",
      "Amaya", "ámbar", "Amelia", "América", "Amets", "Amor", "Amparo", "Ana", "Anabel", "Anaïs",
      "Anastasia",
      "Ane", "ángela", "Angélica", "Angelina", "Angelita", "Ani", "Anna", "Anne", "Anselma",
      "Antía", "Antonia", "Anunciación", "Apolonia", "Araceli", "Aracelis", "Aracely", "Arantxa",
      "Arantzazu",
      "Arcelia", "Argiñe", "Ariadna", "Armida", "Ascensión", "Assumpció", "Asun", "Asunción",
      "Aurelia", "Aurora",
      "Azeneth", "Azucena", "Bakarne", "Balbina", "Bárbara", "Beatriu", "Beatriz", "Belén",
      "Benigna", "Benita",
      "Berezi", "Bernarda", "Bernardita", "Berta", "Bibiana", "Bidane", "Bienvenida", "Bihotz",
      "Blanca",
      "Branca", "Brigida", "Brunilda", "Calista", "Calixta", "Camila", "Candela", "Candelaria",
      "Candelas", "Cándida", "Caridad", "Carina", "Carla", "Carlota", "Carme", "Carmela",
      "Carmelita", "Carmen",
      "Carmina", "Carolina", "Cassandra", "Catalina", "Catarina", "Caterina", "Cayetana",
      "Cecilia", "Celestina",
      "Celia", "Charo", "Chelo", "Chita", "Chus", "Cintia", "Clara", "Clarisa", "Clarissa",
      "Clàudia", "Claudia",
      "Clementina", "Cloe", "Clotilde", "Concepción", "Concha", "Conchita", "Constanza",
      "Consuela", "Consuelo",
      "Coral", "Corona", "Crescencia", "Cristina", "Cruz", "Cruzita", "Custodia", "Dalia",
      "Daniela", "Débora",
      "Delfina", "Delia", "Desideria", "Diana", "Dionisia", "Dolores", "Dolors", "Dominga",
      "Domitila", "Dora",
      "Dores", "Dorita", "Dorotea", "Dulce", "Edelmira", "Ederne", "Edurne", "Eguzkiñe", "Eider",
      "Elba", "Elena",
      "Eli", "Eliana", "Eligia", "Elisa", "Elisabet", "Elixabete", "Elodia", "Eloísa", "Elvira",
      "Ema", "Emelina",
      "Emigdia", "Emilia", "Emiliana", "Emma", "Emperatriz", "Encarna", "Encarnación",
      "Encarnita", "Eneida",
      "Ercilia", "Erlea", "Eskarne", "Esmeralda", "Esperanza", "Estefanía", "Estela", "Ester",
      "Esther", "Esti",
      "Estiñne", "Estrella", "Etelvina", "Eufemia", "Eugenia", "Eukene", "Eulàlia", "Eulalia",
      "Euria", "Eva",
      "Evangelina", "Evelia", "Evita", "Fabiana", "Fabiola", "Fanny", "Fátima", "Febe", "Felicia",
      "Feliciana",
      "Felicidad", "Felipa", "Fernanda", "Fidela", "Fidelia", "Filomena", "Flavia", "Florencia",
      "Florentina",
      "Florina", "Florinda", "Fortunata", "Fran", "Francesca", "Francisca", "Frantziska",
      "Gabriela", "Garbi",
      "Garbiñe", "Garden", "Gema", "Gemma", "Genoveva", "Georgina", "Gertrudis", "Gisela",
      "Gloria", "Goizane",
      "Goizargi", "Goizeder", "Gotzone", "Gracia", "Graciana", "Graciela", "Griselda",
      "Gurutze", "Haizea", "Haydée", "Herminia", "Hilargi", "Hilario", "Hilda", "Hirune",
      "Hortensia", "Ida",
      "Idoya", "Ignacia", "Igone", "Ihintza", "Ileana", "Imelda", "Imma", "Immaculada", "Inés",
      "Inma",
      "Inmaculada", "Irati", "Irene", "Iria", "Iris", "Irma", "Irune", "Isa", "Isabel", "Isabela",
      "Isaura",
      "Isidora", "Itsasne", "Itsaso", "Itxaro", "Itxaso", "Itziar", "Ivette", "Ivonne", "Izar",
      "Izaro",
      "Jacinta", "Jana", "Javiera", "Jennifer", "Jenny", "Jesenia", "Jessenia", "Jessica",
      "Jesusa", "Jimena",
      "Joana", "Joaquima", "Joaquina", "Jone", "Jordana", "Josefa", "Josefina", "Josune",
      "Jovita", "Juana",
      "Juanita", "Judit", "Judith", "Júlia", "Julia", "Juliana", "Julie", "Katalin", "Kattalin",
      "Kistiñe",
      "Laia", "Lara", "Laura", "Laurita", "Leandra", "Leocadia", "Leonor", "Leticia", "Lía",
      "Lídia", "Lidia",
      "Lilia", "Liliana", "Llúcia", "Lluïsa", "Loida", "Lola", "Lolita", "Lore", "Lorea",
      "Lorena", "Lorenza",
      "Lourdes", "Lucía", "Luciana", "Lucila", "Luisa", "Luisina", "Luisita", "Luna", "Lupe",
      "Lupita",
      "Luz", "Macarena", "Macaria", "Magdalena", "Maia", "Maialen", "Maite", "Malena", "Manola",
      "Manu",
      "Manuela", "Manuelita", "Marcela", "Marcia", "Margarida", "Margarita", "Maria", "Mariana",
      "Marianela", "Marianita", "Maribel", "Maricela", "Maricruz", "Marina", "Mariona", "Marisa",
      "Marisela",
      "Marisol", "Maristela", "Marita", "Maritza", "Marta", "Martina", "Martirio", "Martita",
      "Matilde", "Maura",
      "Máxima", "Mayra", "Mayte", "Melania", "Melisa", "Mercè", "Mercedes", "Merche", "Meritxell",
      "Micaela",
      "Miguela", "Milagros", "Mireia", "Miren", "Mireya", "Mirta", "Modesta", "Mónica", "Mònica",
      "Monserrat",
      "Montse", "Montserrat", "Nagore", "Nahia", "Naia", "Naiara", "Narcisa", "Natalia", "Nayara",
      "Nekane",
      "Nélida", "Nere", "Nerea", "Nereida", "Neus", "Nicolasa", "Nidia", "Nieve", "Nikole",
      "Nilda",
      "Noela", "Noelia", "Noemí", "Nohemi", "Núria", "Nuria", "Nydia", "Obdulia", "Octavia",
      "Odalys",
      "Ofelia", "Oihana", "Olalla", "Olga", "Olimpia", "Olivia", "Ona", "Oriana", "Osane", "Paca",
      "Pacífica",
      "Palmira", "Paloma", "Paola", "Paquita", "Pascuala", "Pastora", "Patricia", "Paula",
      "Paulina", "Paz",
      "Pepita", "Perla", "Perlita", "Perpetua", "Petrona", "Pía", "Piedad", "Pilar", "Pili",
      "Primitiva",
      "Priscila", "Prudencia", "Queralt", "Rafaela", "Ramona", "Raquel", "Rayen", "Rebeca",
      "Regina", "Reina",
      "Remedios", "Remei", "Renata", "Reyna", "Ricarda", "Rita", "Roberta", "Robertina", "Rocío",
      "Rosa",
      "Rosalía", "Rosalia", "Rosalina", "Rosalinda", "Rosalva", "Rosenda", "Roser", "Rosita",
      "Roxana",
      "Rufina", "Ruperta", "Rut", "Ruth", "Sabela", "Sabina", "Salomé", "Salud", "Salut",
      "Samanta", "Sancha",
      "Sanchia", "Sandra", "Sara", "Sarita", "Saturnina", "Selena", "Septima", "Serafina",
      "Sílvia", "Silvia",
      "Socorro", "Sofía", "Sofia", "Sol", "Soledad", "Sonia", "Soraya", "Sorne", "Susana",
      "Susanita", "Tamara",
      "Tatiana", "Tecla", "Teodora", "Teófila", "Tere", "Teresa", "Terese", "Teresita", "Tomasa",
      "Trini",
      "Udane", "úrsula", "Usoa", "Uxía", "Uxue", "Valentina", "Valeria", "Varinia", "Vera",
      "Verónica", "Victòria", "Victoria", "Vilma", "Violeta", "Virginia", "Visitación", "Viviana",
      "Ximena",
      "Xiomara", "Xoana", "Xochilt", "Xochitl", "Yadira", "Yamila", "Yenifer", "Yenny", "Yesenia",
      "Yessenia",
      "Yessica", "Yolanda", "Ysabel", "Zaira", "Zoraida", "Zorion", "Zorione", "Zuriñe");
  private static final List<String> LAST_NAMES = Arrays.asList(
      "García", "Fernández", "González", "Rodríguez", "López", "Martínez", "Sánchez", "Pérez",
      "Martín", "Gómez",
      "Ruiz", "Hernández", "Jiménez", "Díaz", "Álvarez", "Moreno", "Muñoz", "Alonso", "Gutiérrez",
      "Romero",
      "Navarro", "Torres", "Domínguez", "Gil", "Vázquez", "Serrano", "Ramos", "Blanco", "Sanz",
      "Castro",
      "Suárez", "Ortega", "Rubio", "Molina", "Delgado", "Ramírez", "Morales", "Ortiz", "Marín",
      "Iglesias");


  @Override
  public boolean accept(final Country country) {
    return Country.ES == country;
  }

  @Override
  public String generateFirstName(final Gender gender) {
    if (gender == Gender.MALE) {
      return RandomUtils.randomFromList(MALE_FIRST_NAMES);
    }
    return RandomUtils.randomFromList(FEMALE_FIRST_NAMES);
  }

  @Override
  public String generateLastName(final Gender gender) {
    return RandomUtils.randomFromList(LAST_NAMES);
  }
}
