package bindings.commons.automation.customer.names;

import com.ipfdigital.automation.customer.Country;
import com.ipfdigital.automation.customer.Gender;
import com.ipfdigital.automation.generators.RandomUtils;

import java.util.Arrays;
import java.util.List;

final class MXNameGeneratorStrategy implements GenerateNameStrategy {

  private static final List<String> MALE_FIRST_NAMES = Arrays.asList(
      "Aarón", "Abel", "Abilio", "Abraha", "Adalberto", "Adán", "Adelardo", "Adolfito", "Adolfo",
      "Adrián",
      "Agapito", "Agustín", "Alberto", "Albino", "Alcides", "Ale", "Alejandro", "Alejo",
      "Alfonso", "Alfredo",
      "Alonso", "álvaro", "Amado", "Amador", "Amancio", "Amando", "Ambrosio", "Américo",
      "Amílcar", "Amor",
      "Anacleto", "Anastasio", "Andrés", "ángel", "Angelino", "Aníbal", "Anselmo", "Antelmo",
      "Antonio",
      "Apolinar", "Aristides", "Armando", "Arsenio", "Artemio", "Arturo", "Asdrubal", "Atilio",
      "Augusto",
      "Aureliano", "Aurelio", "Balbino", "Baldo", "Baldomero", "Balduino", "Baltasar",
      "Bartolomé", "Basilio",
      "Baudelio", "Bautista", "Benigno", "Benito", "Benjamín", "Bermudo", "Bernardino",
      "Bernardo", "Berto",
      "Blas", "Bolívar", "Bonifacio", "Bruno", "Buenaventura", "Calisto", "Calixto", "Camilo",
      "Cande",
      "Candelario", "Cándido", "Carlito", "Carlitos", "Carlos", "Carmelo", "Casimiro", "Cayetano",
      "Cebrián",
      "Cecilio", "Ceferino", "Celestino", "Celino", "Celio", "Celso", "César", "Che", "Chucho",
      "Chus", "Chuy",
      "Cipriano", "Ciríaco", "Ciriaco", "Cirino", "Ciro", "Citlali", "Claudio", "Clemente",
      "Cleto", "Clímaco",
      "Conrado", "Cornelio", "Cristián", "Cristóbal", "Cruz", "Cuauhtémoc", "Curro", "Custodio",
      "Dan", "Dani",
      "Danilo", "Darío", "David", "Demetrio", "Desi", "Desiderio", "Diego", "Dimas", "Dionisio",
      "Domingo", "Donato", "Duilio", "Eberardo", "Edelmiro", "Edgardo", "Edmundo", "Eduardo",
      "Efraín", "Eladio",
      "Eleuterio", "Elías", "Eligio", "Eliseo", "Eloy", "Elpidio", "Emigdio", "Emiliano",
      "Emilio", "Enrique",
      "Epifanio", "Erasmo", "Eric", "Ernesto", "Espiridión", "Estavan", "Esteban", "Eugenio",
      "Eusebio",
      "Eustaquio", "Eutimio", "Eutropio", "Evaristo", "Ezequiel", "Fabián", "Fabio", "Fabricio",
      "Faustino",
      "Fausto", "Federico", "Feliciano", "Felipe", "Félix", "Fermín", "Fernando", "Fidel", "Fito",
      "Flavio",
      "Florencio", "Florentino", "Fortunato", "Fran", "Francisco", "Fulgencio", "Gabino",
      "Gabriel", "Galo",
      "Gaspar", "Gastón", "Geraldo", "Gerardo", "Germán", "Gerónimo", "Gervasio", "Gil",
      "Gilberto", "Glauco",
      "Godofredo", "Gonzalo", "Goyo", "Graciano", "Gregorio", "Guadalupe", "Gualterio",
      "Guillermo", "Guiomar",
      "Gustavo", "Haroldo", "Héctor", "Heliodoro", "Heraclio", "Herberto", "Heriberto",
      "Hermenegildo",
      "Herminio", "Hernán", "Hernando", "Hipólito", "Horacio", "Hugo", "Ignacio", "Ildefonso",
      "íñigo",
      "Inocencio", "Isaías", "Isidoro", "Isidro", "Ismael", "Iván", "Jacinto", "Jacobo", "Jafet",
      "Jaime",
      "Javier", "Jenaro", "Jeremías", "Jerónimo", "Jesús", "Jimeno", "Joaquín", "Joel", "Jonatan",
      "Jordán",
      "Jorge", "José", "Josemaría", "Josepe", "Josué", "Juan", "Juanito", "Julián", "Julio",
      "Kike", "Lalo",
      "Lázaro", "Leandro", "Leocadio", "León", "Leonardo", "Leoncio", "Leopoldo", "Lino",
      "Lisandro", "Lope",
      "Lorenzo", "Loreto", "Lucho", "Luciano", "Lucio", "Luis", "Lupe", "Macario", "Manolo",
      "Manu",
      "Manuel", "Marcelino", "Marcelo", "Marcial", "Marciano", "Marcio", "Marco", "Marcos",
      "Mariano",
      "Marino", "Mario", "Martín", "Mateo", "Matías", "Mauricio", "Maximiano", "Maximiliano",
      "Maximino",
      "Máximo", "Melchor", "Miguel", "Miguelángel", "Miguelito", "Modesto", "Moisés", "Nacho",
      "Nacio", "Nando",
      "Narciso", "Natalio", "Natanael", "Nataniel", "Nazario", "Nico", "Nicodemo", "Nicolás",
      "Noé", "Norberto",
      "Octavio", "Odalis", "Olegario", "Onofre", "Orfeo", "óscar", "Osvaldo", "Ovidio", "Pablo",
      "Paco", "Pancho",
      "Pánfilo", "Paquito", "Pascual", "Pastor", "Patricio", "Paulino", "Pedro", "Pepe", "Pepito",
      "Pío",
      "Plácido", "Plinio", "Poncio", "Porfirio", "Primitivo", "Próspero", "Prudencio", "Quique",
      "Quirino",
      "Rafa", "Rafael", "Raimundo", "Rainerio", "Ramiro", "Ramón", "Raúl", "Raymundo", "Régulo",
      "Reinaldo",
      "Remigio", "Renato", "René", "Reynaldo", "Ricardo", "Rico", "Roberto", "Rodolfito",
      "Rodolfo",
      "Rodrigo", "Rogelio", "Rolando", "Roldán", "Román", "Roque", "Rosario", "Rosendo", "Rubén",
      "Rufino",
      "Ruperto", "Ruy", "Sabas", "Salomón", "Salvador", "Samuel", "Sancho", "Sandalio",
      "Santiago", "Santos",
      "Saturnino", "Sebastián", "Sergio", "Seve", "Severiano", "Severino", "Severo", "Sigfrido",
      "Silvestre",
      "Silvio", "Simón", "Sofronio", "Sosimo", "Tacito", "Tadeo", "Tancredo", "Telmo", "Teo",
      "Teobaldo",
      "Teodoro", "Teodosio", "Teódulo", "Teófilo", "Tercero", "Tiburcio", "Timoteo", "Tito",
      "Tomás", "Toni",
      "Toño", "Toribio", "Trinidad", "Tristán", "Tulio", "Ulises", "Urbano", "Valentín",
      "Valerio", "Valero",
      "Vasco", "Venceslás", "Vicente", "Víctor", "Victorino", "Vidal", "Vinicio", "Virgilio",
      "Vito", "Wilfredo",
      "Xuan", "Yago", "Zacarías");
  private static final List<String> FEMALE_FIRST_NAMES = Arrays.asList(
      "Abigaíl", "Adela", "Adelaida", "Adelia", "Adelina", "Adelita", "Adora", "Adoración",
      "Adriana", "áfrica",
      "Agata", "águeda", "Agustina", "Ainoa", "Alba", "Albina", "Ale", "Alejandra", "Alexandra",
      "Alicia", "Alma",
      "Almudena", "Alondra", "Amada", "Amalia", "Amanda", "Amaranta", "Amarilis", "Amaya",
      "ámbar", "Amelia",
      "América", "Amor", "Amparo", "Ana", "Anabel", "Anastasia", "Andrea", "ángela", "Angélica",
      "Angelina",
      "Angelita", "Ani", "Anita", "Anselma", "Antonia", "Anunciación", "Apolonia", "Araceli",
      "Aracelis",
      "Aracely", "Arcelia", "Ariadna", "Armida", "Ascensión", "Asun", "Asunción", "Aurelia",
      "Aurora", "Azeneth",
      "Azucena", "Balbina", "Bárbara", "Beatriz", "Belén", "Benigna", "Benita", "Bernarda",
      "Bernardita", "Berta",
      "Bibiana", "Bienvenida", "Blanca", "Brigida", "Brunilda", "Calista", "Calixta", "Camila",
      "Cande",
      "Candela", "Candelaria", "Candelas", "Cándida", "Caridad", "Carina", "Carla", "Carlota",
      "Carmela",
      "Carmelita", "Carmen", "Carmina", "Carolina", "Cassandra", "Catalina", "Cayetana",
      "Cecilia", "Celestina",
      "Celia", "Charo", "Chelo", "Chita", "Chus", "Cintia", "Citlali", "Clara", "Clarisa",
      "Clarissa", "Claudia",
      "Clementina", "Cloe", "Clotilde", "Concepción", "Concha", "Conchita", "Constanza",
      "Consuela", "Consuelo",
      "Coral", "Corona", "Crescencia", "Cristina", "Cruz", "Cruzita", "Custodia", "Dalia",
      "Daniela", "Débora",
      "Delfina", "Delia", "Desideria", "Diana", "Dionisia", "Dolores", "Dominga", "Domitila",
      "Dora", "Dorita",
      "Dorotea", "Dulce", "Edelmira", "Elba", "Elena", "Eli", "Eliana", "Eligia", "Elisa",
      "Elisabet", "Elodia",
      "Eloísa", "Elvira", "Ema", "Emelina", "Emigdia", "Emilia", "Emiliana", "Emma", "Emperatriz",
      "Encarna",
      "Encarnación", "Encarnita", "Eneida", "Ercilia", "Esmeralda", "Esperanza", "Estefanía",
      "Estela", "Ester",
      "Esther", "Estrella", "Etelvina", "Eufemia", "Eugenia", "Eulalia", "Eva", "Evangelina",
      "Evelia", "Evita",
      "Fabiana", "Fabiola", "Fanny", "Fátima", "Febe", "Felicia", "Feliciana", "Felicidad",
      "Felipa", "Fernanda",
      "Fidela", "Fidelia", "Filomena", "Flavia", "Florencia", "Florentina", "Florina", "Florinda",
      "Fortunata",
      "Fran", "Francisca", "Gabriela", "Gema", "Genoveva", "Georgina", "Gertrudis", "Gisela",
      "Gloria", "Gracia",
      "Graciana", "Graciela", "Griselda", "Guadalupe", "Guiomar", "Haydée", "Herminia", "Hilario",
      "Hilda",
      "Hortensia", "Ida", "Idoya", "Ignacia", "Ileana", "Imelda", "Inés", "Inma", "Inmaculada",
      "Irene", "Iris",
      "Irma", "Isa", "Isabel", "Isabela", "Isaura", "Isidora", "Itzel", "Itziar", "Ivette",
      "Ivonne", "Jacinta",
      "Javiera", "Jennifer", "Jenny", "Jesenia", "Jessenia", "Jessica", "Jesusa", "Jimena",
      "Joaquina", "Jordana",
      "Josefa", "Josefina", "Jovita", "Juana", "Juanita", "Judit", "Judith", "Julia", "Juliana",
      "Julie", "Lara",
      "Laurita", "Leandra", "Leocadia", "Leonor", "Leticia", "Lidia", "Lilia", "Liliana", "Loida",
      "Lola", "Lolita", "Lorena", "Lorenza", "Loreto", "Lourdes", "Lucía", "Luciana", "Lucila",
      "Luisa",
      "Luisina", "Luisita", "Luna", "Lupe", "Lupita", "Luz", "Macarena", "Macaria", "Magdalena",
      "Maite",
      "Malena", "Manola", "Manu", "Manuela", "Manuelita", "Marcela", "Marcia", "Margarita",
      "María", "Mariana",
      "Marianela", "Marianita", "Maribel", "Maricela", "Maricruz", "Marina", "Marisa", "Marisela",
      "Marisol",
      "Maristela", "Marita", "Maritza", "Marta", "Martina", "Martirio", "Martita", "Matilde",
      "Maura", "Máxima",
      "Mayra", "Mayte", "Melania", "Melisa", "Mercedes", "Merche", "Micaela", "Miguela",
      "Milagros", "Mireia",
      "Mireya", "Mirta", "Modesta", "Mónica", "Narcisa", "Natalia", "Nayara", "Nélida", "Nereida",
      "Nicolasa",
      "Nidia", "Nieve", "Nieves", "Nilda", "Noelia", "Noemí", "Nohemi", "Nuria", "Nydia",
      "Obdulia", "Octavia",
      "Odalis", "Odalys", "Ofelia", "Olalla", "Olga", "Olimpia", "Olivia", "Oriana", "Paca",
      "Pacífica",
      "Palmira", "Paloma", "Paola", "Paquita", "Pascuala", "Pastora", "Patricia", "Paula",
      "Paulina", "Paz",
      "Pepita", "Perla", "Perlita", "Perpetua", "Petrona", "Pía", "Piedad", "Pilar", "Pili",
      "Primitiva",
      "Priscila", "Prudencia", "Rafaela", "Ramona", "Raquel", "Rayen", "Rebeca", "Regina",
      "Reina", "Remedios",
      "Renata", "Reyes", "Reyna", "Ricarda", "Rita", "Roberta", "Robertina", "Rocío", "Rosa",
      "Rosalía",
      "Rosalia", "Rosalina", "Rosalinda", "Rosalva", "Rosario", "Rosenda", "Rosita", "Roxana",
      "Rufina",
      "Ruperta", "Rut", "Ruth", "Sabina", "Sacnite", "Salomé", "Salud", "Samanta", "Sancha",
      "Sanchia",
      "Sara", "Sarita", "Saturnina", "Selena", "Septima", "Serafina", "Silvia", "Socorro",
      "Sofía", "Sol",
      "Soledad", "Sonia", "Soraya", "Susana", "Susanita", "Tamara", "Tatiana", "Tecla", "Teodora",
      "Teófila",
      "Tere", "Teresa", "Teresita", "Tomasa", "Trini", "Trinidad", "úrsula", "Valentina",
      "Valeria", "Varinia",
      "Vera", "Verónica", "Victoria", "Vilma", "Violeta", "Virginia", "Visitación", "Viviana",
      "Ximena",
      "Xiomara", "Xochilt", "Xochitl", "Yadira", "Yamila", "Yenifer", "Yenny", "Yesenia",
      "Yessenia", "Yessica",
      "Yolanda", "Ysabel", "Zaira", "Zoraida");
  private static final List<String> LAST_NAMES = Arrays.asList(
      "Abarca", "Abascal", "Abel", "Abraham", "Acosta", "Agua", "Aguado", "Aiza", "Alamilla",
      "Alfaro",
      "Alvarado", "álvarez", "Amador", "Andrés", "Antúnez", "Aquino", "Araujo", "Araya", "Arce",
      "Arechavaleta",
      "Arenas", "Aritza", "Armando", "Arreola", "Arriola", "Asís", "Asturias", "Banderas",
      "Barros", "Basurto",
      "Bautista", "Bello", "Belmonte", "Benítez", "Bermúdez", "Blanco", "Bolívar", "Bosque",
      "Bustillo", "Busto",
      "Bustos", "Cabello", "Cabrera", "Campana", "Campo", "Campos", "Cantú", "Cardoso", "Cardozo",
      "Caro",
      "Casal", "Casales", "Castellano", "Castilla", "Castillo", "Castro", "Catalán", "Chavarría",
      "Chaves",
      "Chávez", "Colón", "Crespo", "Cruz", "Cuéllar", "Cuesta", "Cuevas", "Dalí", "De La Cruz",
      "De La Fuente",
      "Del Bosque", "De León", "Delgado", "Del Olmo", "De Santiago", "Díaz", "Domínguez",
      "Duarte", "Echevarría",
      "Echeverría", "Elizondo", "Escamilla", "Escárcega", "Escarrà", "Esparza", "Espina",
      "Espino", "Espinosa",
      "Espinoza", "Estévez", "Félix", "Fernández", "Fierro", "Flores", "Fonseca", "Franco",
      "Fuentes", "Gallego",
      "Gallo", "García", "Garza", "Gaspar", "Gómez", "Gonzales", "González", "Guadarrama",
      "Guerra", "Guerrero",
      "Gutiérrez", "Gutierrez", "Hernández", "Herrera", "Herrero", "Hierro", "Holguín", "Huerta",
      "Ibáñez",
      "Ibarra", "Iñíguez", "Jasso", "Jimenez", "Juárez", "Lobo", "Lopez", "Losa", "Loyola",
      "Machado",
      "Macías", "Maradona", "María", "Marino", "Márquez", "Martínez", "Martinez", "Mata",
      "Medina", "Melendez",
      "Méndez", "Mendoza", "Menendez", "Merlo", "Mingo", "Moles", "Molina", "Montero", "Morales",
      "Moralez",
      "Moreno", "Narváez", "Nieves", "Noguerra", "Núñez", "Obando", "Ochoa", "Ojeda", "Ola",
      "Oleastro", "Olguin",
      "Olmo", "Olmos", "Oquendo", "Orellana", "Ortega", "Ortiz", "Palomo", "Paredes", "Pavia",
      "Peláez", "Peña",
      "Pérez", "Perez", "Porras", "Prieto", "Puerta", "Puga", "Puig", "Quinones", "Quintana",
      "Quirós", "Ramírez",
      "Ramos", "Rana", "Rendón", "Rey", "Reyes", "Rios", "Rivera", "Rivero", "Robledo", "Robles",
      "Rodríguez",
      "Rodriquez", "Rojas", "Rojo", "Roldán", "Romero", "Rosales", "Rubio", "Ruiz", "Sala",
      "Salamanca",
      "Salazar", "Salcedo", "Salinas", "Sanchez", "Sandoval", "San Nicolas", "Santana",
      "Santiago", "Santillian",
      "Santos", "Sastre", "Sepúlveda", "Sierra", "Silva", "Solos", "Soto", "Suárez", "Suero",
      "Tapia", "Terrazas",
      "Torres", "Tos", "Travieso", "Trujillo", "Ubina", "Urbina", "Ureña", "Valdez", "Valencia",
      "Varela",
      "Vargas", "Vásquez", "Vázquez", "Vega", "Vela", "Velásquez", "Velázquez", "Ventura",
      "Vicario", "Villa",
      "Villalobos", "Villanueva", "Villaverde", "Viteri", "Ybarra", "Zamorano", "Zapatero",
      "Zavala",
      "Zubizarreta");

  @Override
  public boolean accept(final Country country) {
    return Country.MX == country;
  }

  @Override
  public String generateFirstName(final Gender gender) {
    if (gender == Gender.MALE) {
      return RandomUtils.randomFromList(MALE_FIRST_NAMES);
    }
    return RandomUtils.randomFromList(FEMALE_FIRST_NAMES);
  }

  @Override
  public String generateLastName(final Gender gender) {
    return RandomUtils.randomFromList(LAST_NAMES);
  }
}
