//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.06 at 03:53:27 PM CET
//


package bindings.commons.automation.mule.model.mule.development.bluecashws.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransferList" type="{http://ipfdigital.com/Mule/BlueCash/AIO/Channel}TransferList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transferList"
})
@XmlRootElement(name = "MakeTransfersRequest")
public class MakeTransfersRequest {

  @XmlElement(name = "TransferList", required = true)
  protected TransferList transferList;

  /**
   * Gets the value of the transferList property.
   * 
   * @return possible object is {@link TransferList }
   * 
   */
  public TransferList getTransferList() {
    return this.transferList;
  }

  /**
   * Sets the value of the transferList property.
   * 
   * @param value allowed object is {@link TransferList }
   * 
   */
  public void setTransferList(final TransferList value) {
    this.transferList = value;
  }

}
