//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.06 at 03:53:27 PM CET
//


package bindings.commons.automation.mule.model.mule.development.bluecashws.aio.channel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the com.ipfdigital.automation.mule.model.mule.development.bluecashws.aio.channel
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes
   * for package: com.ipfdigital.automation.mule.model.mule.development.bluecashws.aio.channel
   * 
   */
  public ObjectFactory() {
    // New ObjectFactory
  }

  /**
   * Create an instance of {@link MakeTransfersResponse }
   * 
   */
  public MakeTransfersResponse createMakeTransfersResponse() {
    return new MakeTransfersResponse();
  }

  /**
   * Create an instance of {@link RetryTransfersResponse }
   * 
   */
  public RetryTransfersResponse createRetryTransfersResponse() {
    return new RetryTransfersResponse();
  }

  /**
   * Create an instance of {@link MakeTransfersRequest }
   * 
   */
  public MakeTransfersRequest createMakeTransfersRequest() {
    return new MakeTransfersRequest();
  }

  /**
   * Create an instance of {@link TransferList }
   * 
   */
  public TransferList createTransferList() {
    return new TransferList();
  }

  /**
   * Create an instance of {@link StatusResponseType }
   * 
   */
  public StatusResponseType createStatusResponseType() {
    return new StatusResponseType();
  }

  /**
   * Create an instance of {@link MakeTransfersResponse.TransfersListResponse }
   * 
   */
  public MakeTransfersResponse.TransfersListResponse createMakeTransfersResponseTransfersListResponse() {
    return new MakeTransfersResponse.TransfersListResponse();
  }

  /**
   * Create an instance of {@link RetryTransfersRequest }
   * 
   */
  public RetryTransfersRequest createRetryTransfersRequest() {
    return new RetryTransfersRequest();
  }

  /**
   * Create an instance of {@link RetryTransferList }
   * 
   */
  public RetryTransferList createRetryTransferList() {
    return new RetryTransferList();
  }

  /**
   * Create an instance of {@link RetryTransfersResponse.RetryTransferListResponse }
   * 
   */
  public RetryTransfersResponse.RetryTransferListResponse createRetryTransfersResponseRetryTransferListResponse() {
    return new RetryTransfersResponse.RetryTransferListResponse();
  }

  /**
   * Create an instance of {@link RetryTransfer }
   * 
   */
  public RetryTransfer createRetryTransfer() {
    return new RetryTransfer();
  }

  /**
   * Create an instance of {@link RetryTransferResponse }
   * 
   */
  public RetryTransferResponse createRetryTransferResponse() {
    return new RetryTransferResponse();
  }

  /**
   * Create an instance of {@link Transfer }
   * 
   */
  public Transfer createTransfer() {
    return new Transfer();
  }

  /**
   * Create an instance of {@link TransferResponse }
   * 
   */
  public TransferResponse createTransferResponse() {
    return new TransferResponse();
  }

}
