//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.06 at 03:53:27 PM CET
//


package bindings.commons.automation.mule.model.mule.development.bluecashws.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseStatus" type="{http://ipfdigital.com/Mule/BlueCash/AIO/Channel}StatusResponseType"/&gt;
 *         &lt;element name="RetryTransferListResponse"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="RetryTransferResponse" type="{http://ipfdigital.com/Mule/BlueCash/AIO/Channel}RetryTransferResponse" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "responseStatus",
    "retryTransferListResponse"
})
@XmlRootElement(name = "RetryTransfersResponse")
public class RetryTransfersResponse {

  @XmlElement(name = "ResponseStatus", required = true)
  protected StatusResponseType responseStatus;
  @XmlElement(name = "RetryTransferListResponse", required = true)
  protected RetryTransferListResponse retryTransferListResponse;

  /**
   * Gets the value of the responseStatus property.
   *
   * @return possible object is {@link StatusResponseType }
   *
   */
  public StatusResponseType getResponseStatus() {
    return this.responseStatus;
  }

  /**
   * Sets the value of the responseStatus property.
   *
   * @param value allowed object is {@link StatusResponseType }
   *
   */
  public void setResponseStatus(final StatusResponseType value) {
    this.responseStatus = value;
  }

  /**
   * Gets the value of the retryTransferListResponse property.
   *
   * @return possible object is {@link RetryTransferListResponse }
   *
   */
  public RetryTransferListResponse getRetryTransferListResponse() {
    return this.retryTransferListResponse;
  }

  /**
   * Sets the value of the retryTransferListResponse property.
   *
   * @param value allowed object is {@link RetryTransferListResponse }
   *
   */
  public void setRetryTransferListResponse(final RetryTransferListResponse value) {
    this.retryTransferListResponse = value;
  }


  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType&gt;
   *   &lt;complexContent&gt;
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
   *       &lt;sequence&gt;
   *         &lt;element name="RetryTransferResponse" type="{http://ipfdigital.com/Mule/BlueCash/AIO/Channel}RetryTransferResponse" maxOccurs="unbounded" minOccurs="0"/&gt;
   *       &lt;/sequence&gt;
   *     &lt;/restriction&gt;
   *   &lt;/complexContent&gt;
   * &lt;/complexType&gt;
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = {
      "retryTransferResponse"
  })
  public static class RetryTransferListResponse {

    @XmlElement(name = "RetryTransferResponse")
    protected List<RetryTransferResponse> retryTransferResponse;

    /**
     * Gets the value of the retryTransferResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the retryTransferResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getRetryTransferResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link RetryTransferResponse }
     * 
     * 
     */
    public List<RetryTransferResponse> getRetryTransferResponse() {
      if (this.retryTransferResponse == null) {
        this.retryTransferResponse = new ArrayList<>();
      }
      return this.retryTransferResponse;
    }

  }

}
