//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.06 at 03:53:27 PM CET
//


package bindings.commons.automation.mule.model.mule.development.bluecashws.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RetryTransferList" type="{http://ipfdigital.com/Mule/BlueCash/AIO/Channel}RetryTransferList"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retryTransferList"
})
@XmlRootElement(name = "RetryTransfersRequest")
public class RetryTransfersRequest {

  @XmlElement(name = "RetryTransferList", required = true)
  protected RetryTransferList retryTransferList;

  /**
   * Gets the value of the retryTransferList property.
   * 
   * @return possible object is {@link RetryTransferList }
   * 
   */
  public RetryTransferList getRetryTransferList() {
    return this.retryTransferList;
  }

  /**
   * Sets the value of the retryTransferList property.
   * 
   * @param value allowed object is {@link RetryTransferList }
   * 
   */
  public void setRetryTransferList(final RetryTransferList value) {
    this.retryTransferList = value;
  }

}
