//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.06 at 03:53:27 PM CET
//


package bindings.commons.automation.mule.model.mule.development.bluecashws.aio.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigDecimal;


/**
 * <p>
 * Java class for Transfer complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transfer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransferAppId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ReceiverAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderAccount" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SenderAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderMobile" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SenderEmail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transfer", propOrder = {
    "transferAppId",
    "amount",
    "title",
    "receiverAccount",
    "receiverName",
    "receiverAddress",
    "currency",
    "senderAccount",
    "senderName",
    "senderAddress",
    "senderMobile",
    "senderEmail"
})
public class Transfer {

  @XmlElement(name = "TransferAppId", required = true)
  protected String transferAppId;
  @XmlElement(name = "Amount", required = true)
  protected BigDecimal amount;
  @XmlElement(name = "Title", required = true)
  protected String title;
  @XmlElement(name = "ReceiverAccount", required = true)
  protected String receiverAccount;
  @XmlElement(name = "ReceiverName", required = true)
  protected String receiverName;
  @XmlElement(name = "ReceiverAddress")
  protected String receiverAddress;
  @XmlElement(name = "Currency", required = true)
  protected String currency;
  @XmlElement(name = "SenderAccount", required = true)
  protected String senderAccount;
  @XmlElement(name = "SenderName", required = true)
  protected String senderName;
  @XmlElement(name = "SenderAddress")
  protected String senderAddress;
  @XmlElement(name = "SenderMobile")
  protected String senderMobile;
  @XmlElement(name = "SenderEmail")
  protected String senderEmail;

  /**
   * Gets the value of the transferAppId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTransferAppId() {
    return this.transferAppId;
  }

  /**
   * Sets the value of the transferAppId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTransferAppId(final String value) {
    this.transferAppId = value;
  }

  /**
   * Gets the value of the amount property.
   * 
   * @return possible object is {@link BigDecimal }
   * 
   */
  public BigDecimal getAmount() {
    return this.amount;
  }

  /**
   * Sets the value of the amount property.
   * 
   * @param value allowed object is {@link BigDecimal }
   * 
   */
  public void setAmount(final BigDecimal value) {
    this.amount = value;
  }

  /**
   * Gets the value of the title property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTitle() {
    return this.title;
  }

  /**
   * Sets the value of the title property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTitle(final String value) {
    this.title = value;
  }

  /**
   * Gets the value of the receiverAccount property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReceiverAccount() {
    return this.receiverAccount;
  }

  /**
   * Sets the value of the receiverAccount property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setReceiverAccount(final String value) {
    this.receiverAccount = value;
  }

  /**
   * Gets the value of the receiverName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReceiverName() {
    return this.receiverName;
  }

  /**
   * Sets the value of the receiverName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setReceiverName(final String value) {
    this.receiverName = value;
  }

  /**
   * Gets the value of the receiverAddress property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getReceiverAddress() {
    return this.receiverAddress;
  }

  /**
   * Sets the value of the receiverAddress property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setReceiverAddress(final String value) {
    this.receiverAddress = value;
  }

  /**
   * Gets the value of the currency property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCurrency() {
    return this.currency;
  }

  /**
   * Sets the value of the currency property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setCurrency(final String value) {
    this.currency = value;
  }

  /**
   * Gets the value of the senderAccount property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderAccount() {
    return this.senderAccount;
  }

  /**
   * Sets the value of the senderAccount property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderAccount(final String value) {
    this.senderAccount = value;
  }

  /**
   * Gets the value of the senderName property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderName() {
    return this.senderName;
  }

  /**
   * Sets the value of the senderName property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderName(final String value) {
    this.senderName = value;
  }

  /**
   * Gets the value of the senderAddress property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderAddress() {
    return this.senderAddress;
  }

  /**
   * Sets the value of the senderAddress property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderAddress(final String value) {
    this.senderAddress = value;
  }

  /**
   * Gets the value of the senderMobile property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderMobile() {
    return this.senderMobile;
  }

  /**
   * Sets the value of the senderMobile property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderMobile(final String value) {
    this.senderMobile = value;
  }

  /**
   * Gets the value of the senderEmail property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getSenderEmail() {
    return this.senderEmail;
  }

  /**
   * Sets the value of the senderEmail property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setSenderEmail(final String value) {
    this.senderEmail = value;
  }

}
