package bindings.commons.automation.generator.model.aio.dao;

public enum Event {
  CONTRACT_CREATION,
  DRAW,
  INVOICE_GENERATION,
  INVOICE_CANCELLATION,
  CHANGE_DUE_DATE,
  PAYMENT_HOLIDAY,
  CONTRACT_CHANGE,
  DUE_DATE_REMINDER,
  PAYMENT_HOLIDAY_CANCELLATION,
  REPAYMENT_OPTION_PLAN,
  REPAYMENT_OPTION_PLAN_CANCELLATION,
  CONTRACT_FREEZE,
  CHANGE_UNFREEZE_DATE,
  MEDICARE,
  HOME_INSURANCE,
  BILL_PROTECTOR,
  CALMA,
  CARDIF,
  METLIFE,
  WITHDRAWAL,
  MANUAL

}
