//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.05 at 10:43:19 AM CET
//


package bindings.commons.automation.mule.model.mule.development.bluecashws.bm.channel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Result" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="TransferAppId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Hash" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "result",
    "transferAppId",
    "hash"
})
@XmlRootElement(name = "BlueCashTransferStatusResp")
public class BlueCashTransferStatusResp {

  @XmlElement(name = "Result")
  protected int result;
  @XmlElement(name = "TransferAppId", required = true)
  protected String transferAppId;
  @XmlElement(name = "Hash", required = true)
  protected String hash;

  /**
   * Gets the value of the result property.
   * 
   */
  public int getResult() {
    return this.result;
  }

  /**
   * Sets the value of the result property.
   * 
   */
  public void setResult(final int value) {
    this.result = value;
  }

  /**
   * Gets the value of the transferAppId property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getTransferAppId() {
    return this.transferAppId;
  }

  /**
   * Sets the value of the transferAppId property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setTransferAppId(final String value) {
    this.transferAppId = value;
  }

  /**
   * Gets the value of the hash property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getHash() {
    return this.hash;
  }

  /**
   * Sets the value of the hash property.
   * 
   * @param value allowed object is {@link String }
   * 
   */
  public void setHash(final String value) {
    this.hash = value;
  }

}
