//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.03.05 at 10:43:19 AM CET
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://payment.blue.pl/bluecash")
package bindings.commons.automation.mule.model.mule.development.bluecashws.bm.channel;
