package bindings.commons.automation.customer;

public enum LoanPurpose {

  KITCHEN_APPLIANCES,
  HOME_ENTERTAINMENT,
  APPLIANCE_REPAIR,
  FURNITURE_PURCHASE,
  TOOLS_GARDEN_EQUIPMENT,
  KITCHEN_RENOVATION,
  BATHROOM_RENOVATION,
  BEDROOM_RENOVATION,
  LIVING_ROOM_RENOVATION,
  OUTDOOR_LANDSCAPE,
  OTHER
}
